"""Integration Memory data types — tree structure and sync outcome models.

[INPUT]
- pydantic::BaseModel (POS: Validation + serialisation)
- datetime, uuid (POS: Standard library)

[OUTPUT]
- IntegrationNodeKind: Enum for tree node classification (ROOT/PROVIDER/ACCOUNT/CATEGORY/LEAF)
- IntegrationLeaf: Raw data fetched from an external service
- IntegrationTree: Adaptive hierarchical summary tree metadata
- IntegrationSyncOutcome: Per-item fetch outcome enum
- IntegrationSyncResult: Aggregated sync report

[POS]
Pure data layer for Integration Memory. No I/O, no storage dependencies.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum
from uuid import uuid4

from pydantic import BaseModel, Field, field_validator


class IntegrationNodeKind(StrEnum):
    """Node classification within the integration summary tree.

    The tree uses adaptive branching: depth is determined by data volume
    rather than a fixed schema. When a branch accumulates more than
    a configurable leaf threshold, a new category level is inserted.
    """

    ROOT = "root"
    PROVIDER = "provider"
    ACCOUNT = "account"
    CATEGORY = "category"
    LEAF = "leaf"


class IntegrationSyncOutcome(StrEnum):
    CREATED = "created"
    UPDATED = "updated"
    SKIPPED = "skipped"
    FAILED = "failed"


class IntegrationLeaf(BaseModel):
    """A single data record fetched from an external service.

    This is the inbound DTO before being converted to IntegrationMemory
    and stored in the vector/graph backends.
    """

    id: str = Field(default_factory=lambda: str(uuid4()))
    provider: str = Field(..., description="e.g. 'gmail', 'github', 'slack', 'notion'")
    account_key: str = Field(default="", description="Stable account identifier")
    account_label: str = Field(default="", description="Human-readable account label")
    source_type: str = Field(default="", description="Object type, e.g. 'email', 'pr', 'message'")
    external_object_id: str = Field(default="", description="Provider-side unique ID")
    external_object_type: str = Field(default="", description="Provider-side type label")
    title: str = Field(default="")
    content: str = Field(default="", description="Full text content for embedding")
    summary: str = Field(default="", description="Short summary for tree aggregation")
    tags: list[str] = Field(default_factory=list)
    observed_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    metadata: dict[str, str | int | float | bool] = Field(default_factory=dict)

    @field_validator("observed_at", mode="before")
    @classmethod
    def _ensure_utc(cls, v: datetime | None) -> datetime | None:
        if v is None:
            return None
        if isinstance(v, datetime) and v.tzinfo is None:
            return v.replace(tzinfo=UTC)
        return v


class IntegrationTree(BaseModel):
    """Metadata for an integration summary tree instance.

    Each tree corresponds to one (provider, account_key) pair and holds
    the top-level summary generated by the summariser.
    """

    id: str = Field(default_factory=lambda: str(uuid4()))
    provider: str
    account_key: str = ""
    account_label: str = ""
    root_summary: str = Field(default="", description="Top-level summary of all leaves")
    leaf_count: int = Field(default=0, ge=0)
    last_synced_at: datetime | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    @field_validator("last_synced_at", "created_at", "updated_at", mode="before")
    @classmethod
    def _ensure_utc(cls, v: datetime | None) -> datetime | None:
        if v is None:
            return None
        if isinstance(v, datetime) and v.tzinfo is None:
            return v.replace(tzinfo=UTC)
        return v


class IntegrationSyncResult(BaseModel):
    """Aggregated report of a single sync run."""

    tree_id: str
    provider: str
    account_key: str = ""
    created: int = 0
    updated: int = 0
    skipped: int = 0
    failed: int = 0
    errors: list[str] = Field(default_factory=list)
    new_items: list[dict[str, str]] = Field(
        default_factory=list, description="Structured dicts of newly created items for auto-seeding"
    )
    elapsed_seconds: float = 0.0
    finished_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    @property
    def total_processed(self) -> int:
        return self.created + self.updated + self.skipped + self.failed

    @property
    def success_rate(self) -> float:
        total = self.total_processed
        if total == 0:
            return 1.0
        return (self.created + self.updated + self.skipped) / total
