"""Git safe subcommand configurations for flag-level validation.

All git read-only subcommand configs. Keys are subcommand tokens joined by
space (e.g. "diff", "stash list"). Longer prefixes are matched first by the
classifier engine.

[INPUT]
- (none)

[OUTPUT]
- (none)

[POS]
Git safe subcommand configurations for flag-level validation.
"""

from __future__ import annotations

from myrm_agent_harness.toolkits.code_execution.security.safe_command_configs._git_flags import (
    AUTHOR_FILTER,
    COLOR,
    COUNT,
    DATE_FILTER,
    LOG_DISPLAY,
    PATCH,
    REF_SELECTION,
    STAT,
    branch_positional_dangerous,
    reflog_positional_dangerous,
    remote_positional_dangerous,
    remote_show_positional_dangerous,
    tag_positional_dangerous,
)
from myrm_agent_harness.toolkits.code_execution.security.safe_command_configs.types import (
    FlagArgType,
    SubcommandConfig,
)

GIT_SAFE_SUBCOMMANDS: dict[str, SubcommandConfig] = {
    "diff": SubcommandConfig(
        safe_flags={
            **STAT,
            **COLOR,
            "--dirstat": FlagArgType.NONE,
            "--summary": FlagArgType.NONE,
            "--patch-with-stat": FlagArgType.NONE,
            "--word-diff": FlagArgType.NONE,
            "--word-diff-regex": FlagArgType.STRING,
            "--color-words": FlagArgType.NONE,
            "--no-renames": FlagArgType.NONE,
            "--no-ext-diff": FlagArgType.NONE,
            "--check": FlagArgType.NONE,
            "--ws-error-highlight": FlagArgType.STRING,
            "--full-index": FlagArgType.NONE,
            "--binary": FlagArgType.NONE,
            "--abbrev": FlagArgType.NUMBER,
            "--break-rewrites": FlagArgType.NONE,
            "--find-renames": FlagArgType.NONE,
            "--find-copies": FlagArgType.NONE,
            "--find-copies-harder": FlagArgType.NONE,
            "--irreversible-delete": FlagArgType.NONE,
            "--diff-algorithm": FlagArgType.STRING,
            "--histogram": FlagArgType.NONE,
            "--patience": FlagArgType.NONE,
            "--minimal": FlagArgType.NONE,
            "--ignore-space-at-eol": FlagArgType.NONE,
            "--ignore-space-change": FlagArgType.NONE,
            "--ignore-all-space": FlagArgType.NONE,
            "--ignore-blank-lines": FlagArgType.NONE,
            "--inter-hunk-context": FlagArgType.NUMBER,
            "--function-context": FlagArgType.NONE,
            "--exit-code": FlagArgType.NONE,
            "--quiet": FlagArgType.NONE,
            "--cached": FlagArgType.NONE,
            "--staged": FlagArgType.NONE,
            "--pickaxe-regex": FlagArgType.NONE,
            "--pickaxe-all": FlagArgType.NONE,
            "--no-index": FlagArgType.NONE,
            "--relative": FlagArgType.STRING,
            "--diff-filter": FlagArgType.STRING,
            "-p": FlagArgType.NONE,
            "-u": FlagArgType.NONE,
            "-s": FlagArgType.NONE,
            "-M": FlagArgType.NONE,
            "-C": FlagArgType.NONE,
            "-B": FlagArgType.NONE,
            "-D": FlagArgType.NONE,
            "-l": FlagArgType.NONE,
            "-S": FlagArgType.STRING,
            "-G": FlagArgType.STRING,
            "-O": FlagArgType.STRING,
            "-R": FlagArgType.NONE,
        },
    ),
    "log": SubcommandConfig(
        safe_flags={
            **LOG_DISPLAY,
            **REF_SELECTION,
            **DATE_FILTER,
            **COUNT,
            **STAT,
            **COLOR,
            **PATCH,
            **AUTHOR_FILTER,
            "--abbrev-commit": FlagArgType.NONE,
            "--full-history": FlagArgType.NONE,
            "--dense": FlagArgType.NONE,
            "--sparse": FlagArgType.NONE,
            "--simplify-merges": FlagArgType.NONE,
            "--ancestry-path": FlagArgType.NONE,
            "--source": FlagArgType.NONE,
            "--first-parent": FlagArgType.NONE,
            "--merges": FlagArgType.NONE,
            "--no-merges": FlagArgType.NONE,
            "--reverse": FlagArgType.NONE,
            "--walk-reflogs": FlagArgType.NONE,
            "--skip": FlagArgType.NUMBER,
            "--max-age": FlagArgType.NUMBER,
            "--min-age": FlagArgType.NUMBER,
            "--no-min-parents": FlagArgType.NONE,
            "--no-max-parents": FlagArgType.NONE,
            "--follow": FlagArgType.NONE,
            "--no-walk": FlagArgType.NONE,
            "--left-right": FlagArgType.NONE,
            "--cherry-mark": FlagArgType.NONE,
            "--cherry-pick": FlagArgType.NONE,
            "--boundary": FlagArgType.NONE,
            "--topo-order": FlagArgType.NONE,
            "--date-order": FlagArgType.NONE,
            "--author-date-order": FlagArgType.NONE,
            "--pretty": FlagArgType.STRING,
            "--format": FlagArgType.STRING,
            "--diff-filter": FlagArgType.STRING,
            "-S": FlagArgType.STRING,
            "-G": FlagArgType.STRING,
            "--pickaxe-regex": FlagArgType.NONE,
            "--pickaxe-all": FlagArgType.NONE,
        },
    ),
    "show": SubcommandConfig(
        safe_flags={
            **LOG_DISPLAY,
            **STAT,
            **COLOR,
            **PATCH,
            "--abbrev-commit": FlagArgType.NONE,
            "--word-diff": FlagArgType.NONE,
            "--word-diff-regex": FlagArgType.STRING,
            "--color-words": FlagArgType.NONE,
            "--pretty": FlagArgType.STRING,
            "--format": FlagArgType.STRING,
            "--first-parent": FlagArgType.NONE,
            "--raw": FlagArgType.NONE,
            "--diff-filter": FlagArgType.STRING,
            "-m": FlagArgType.NONE,
            "--quiet": FlagArgType.NONE,
        },
    ),
    "status": SubcommandConfig(
        safe_flags={
            "--short": FlagArgType.NONE,
            "-s": FlagArgType.NONE,
            "--branch": FlagArgType.NONE,
            "-b": FlagArgType.NONE,
            "--porcelain": FlagArgType.NONE,
            "--long": FlagArgType.NONE,
            "--verbose": FlagArgType.NONE,
            "-v": FlagArgType.NONE,
            "--untracked-files": FlagArgType.STRING,
            "-u": FlagArgType.STRING,
            "--ignored": FlagArgType.NONE,
            "--ignore-submodules": FlagArgType.STRING,
            "--column": FlagArgType.NONE,
            "--no-column": FlagArgType.NONE,
            "--ahead-behind": FlagArgType.NONE,
            "--no-ahead-behind": FlagArgType.NONE,
            "--renames": FlagArgType.NONE,
            "--no-renames": FlagArgType.NONE,
            "--find-renames": FlagArgType.STRING,
            "-M": FlagArgType.STRING,
        },
    ),
    "blame": SubcommandConfig(
        safe_flags={
            **COLOR,
            "-L": FlagArgType.STRING,
            "--porcelain": FlagArgType.NONE,
            "-p": FlagArgType.NONE,
            "--line-porcelain": FlagArgType.NONE,
            "--incremental": FlagArgType.NONE,
            "--root": FlagArgType.NONE,
            "--show-stats": FlagArgType.NONE,
            "--show-name": FlagArgType.NONE,
            "--show-number": FlagArgType.NONE,
            "-n": FlagArgType.NONE,
            "--show-email": FlagArgType.NONE,
            "-e": FlagArgType.NONE,
            "-f": FlagArgType.NONE,
            "--date": FlagArgType.STRING,
            "-w": FlagArgType.NONE,
            "--ignore-rev": FlagArgType.STRING,
            "--ignore-revs-file": FlagArgType.STRING,
            "-M": FlagArgType.NONE,
            "-C": FlagArgType.NONE,
            "--score-debug": FlagArgType.NONE,
            "--abbrev": FlagArgType.NUMBER,
            "-s": FlagArgType.NONE,
            "-l": FlagArgType.NONE,
            "-t": FlagArgType.NONE,
        },
    ),
    "shortlog": SubcommandConfig(
        safe_flags={
            **REF_SELECTION,
            **DATE_FILTER,
            "-s": FlagArgType.NONE,
            "--summary": FlagArgType.NONE,
            "-n": FlagArgType.NONE,
            "--numbered": FlagArgType.NONE,
            "-e": FlagArgType.NONE,
            "--email": FlagArgType.NONE,
            "-c": FlagArgType.NONE,
            "--committer": FlagArgType.NONE,
            "--group": FlagArgType.STRING,
            "--format": FlagArgType.STRING,
            "--no-merges": FlagArgType.NONE,
            "--author": FlagArgType.STRING,
        },
    ),
    "ls-files": SubcommandConfig(
        safe_flags={
            "--cached": FlagArgType.NONE,
            "-c": FlagArgType.NONE,
            "--deleted": FlagArgType.NONE,
            "-d": FlagArgType.NONE,
            "--modified": FlagArgType.NONE,
            "-m": FlagArgType.NONE,
            "--others": FlagArgType.NONE,
            "-o": FlagArgType.NONE,
            "--ignored": FlagArgType.NONE,
            "-i": FlagArgType.NONE,
            "--stage": FlagArgType.NONE,
            "-s": FlagArgType.NONE,
            "--killed": FlagArgType.NONE,
            "-k": FlagArgType.NONE,
            "--unmerged": FlagArgType.NONE,
            "-u": FlagArgType.NONE,
            "--directory": FlagArgType.NONE,
            "--no-empty-directory": FlagArgType.NONE,
            "--eol": FlagArgType.NONE,
            "--full-name": FlagArgType.NONE,
            "--abbrev": FlagArgType.NUMBER,
            "--debug": FlagArgType.NONE,
            "-z": FlagArgType.NONE,
            "-t": FlagArgType.NONE,
            "-v": FlagArgType.NONE,
            "-f": FlagArgType.NONE,
            "--exclude": FlagArgType.STRING,
            "-x": FlagArgType.STRING,
            "--exclude-from": FlagArgType.STRING,
            "-X": FlagArgType.STRING,
            "--exclude-per-directory": FlagArgType.STRING,
            "--exclude-standard": FlagArgType.NONE,
            "--error-unmatch": FlagArgType.NONE,
            "--recurse-submodules": FlagArgType.NONE,
        },
    ),
    "rev-parse": SubcommandConfig(
        safe_flags={
            "--verify": FlagArgType.NONE,
            "--short": FlagArgType.STRING,
            "--abbrev-ref": FlagArgType.NONE,
            "--symbolic": FlagArgType.NONE,
            "--symbolic-full-name": FlagArgType.NONE,
            "--show-toplevel": FlagArgType.NONE,
            "--show-cdup": FlagArgType.NONE,
            "--show-prefix": FlagArgType.NONE,
            "--git-dir": FlagArgType.NONE,
            "--git-common-dir": FlagArgType.NONE,
            "--absolute-git-dir": FlagArgType.NONE,
            "--show-superproject-working-tree": FlagArgType.NONE,
            "--is-inside-work-tree": FlagArgType.NONE,
            "--is-inside-git-dir": FlagArgType.NONE,
            "--is-bare-repository": FlagArgType.NONE,
            "--is-shallow-repository": FlagArgType.NONE,
            "--is-shallow-update": FlagArgType.NONE,
            "--path-prefix": FlagArgType.NONE,
        },
    ),
    "describe": SubcommandConfig(
        safe_flags={
            "--tags": FlagArgType.NONE,
            "--match": FlagArgType.STRING,
            "--exclude": FlagArgType.STRING,
            "--long": FlagArgType.NONE,
            "--abbrev": FlagArgType.NUMBER,
            "--always": FlagArgType.NONE,
            "--contains": FlagArgType.NONE,
            "--first-match": FlagArgType.NONE,
            "--exact-match": FlagArgType.NONE,
            "--candidates": FlagArgType.NUMBER,
            "--dirty": FlagArgType.NONE,
            "--broken": FlagArgType.NONE,
        },
    ),
    "cat-file": SubcommandConfig(
        safe_flags={
            "-t": FlagArgType.NONE,
            "-s": FlagArgType.NONE,
            "-p": FlagArgType.NONE,
            "-e": FlagArgType.NONE,
            "--batch-check": FlagArgType.NONE,
            "--allow-undetermined-type": FlagArgType.NONE,
        },
    ),
    "merge-base": SubcommandConfig(
        safe_flags={
            "--is-ancestor": FlagArgType.NONE,
            "--fork-point": FlagArgType.NONE,
            "--octopus": FlagArgType.NONE,
            "--independent": FlagArgType.NONE,
            "--all": FlagArgType.NONE,
        },
    ),
    "rev-list": SubcommandConfig(
        safe_flags={
            **REF_SELECTION,
            **DATE_FILTER,
            **COUNT,
            **AUTHOR_FILTER,
            "--count": FlagArgType.NONE,
            "--reverse": FlagArgType.NONE,
            "--first-parent": FlagArgType.NONE,
            "--ancestry-path": FlagArgType.NONE,
            "--merges": FlagArgType.NONE,
            "--no-merges": FlagArgType.NONE,
            "--min-parents": FlagArgType.NUMBER,
            "--max-parents": FlagArgType.NUMBER,
            "--no-min-parents": FlagArgType.NONE,
            "--no-max-parents": FlagArgType.NONE,
            "--skip": FlagArgType.NUMBER,
            "--max-age": FlagArgType.NUMBER,
            "--min-age": FlagArgType.NUMBER,
            "--walk-reflogs": FlagArgType.NONE,
            "--oneline": FlagArgType.NONE,
            "--abbrev-commit": FlagArgType.NONE,
            "--pretty": FlagArgType.STRING,
            "--format": FlagArgType.STRING,
            "--abbrev": FlagArgType.NUMBER,
            "--full-history": FlagArgType.NONE,
            "--dense": FlagArgType.NONE,
            "--sparse": FlagArgType.NONE,
            "--source": FlagArgType.NONE,
            "--graph": FlagArgType.NONE,
        },
    ),
    "for-each-ref": SubcommandConfig(
        safe_flags={
            "--format": FlagArgType.STRING,
            "--sort": FlagArgType.STRING,
            "--count": FlagArgType.NUMBER,
            "--contains": FlagArgType.STRING,
            "--no-contains": FlagArgType.STRING,
            "--merged": FlagArgType.STRING,
            "--no-merged": FlagArgType.STRING,
            "--points-at": FlagArgType.STRING,
        },
    ),
    "grep": SubcommandConfig(
        safe_flags={
            "-e": FlagArgType.STRING,
            "-E": FlagArgType.NONE,
            "--extended-regexp": FlagArgType.NONE,
            "-G": FlagArgType.NONE,
            "--basic-regexp": FlagArgType.NONE,
            "-F": FlagArgType.NONE,
            "--fixed-strings": FlagArgType.NONE,
            "-P": FlagArgType.NONE,
            "--perl-regexp": FlagArgType.NONE,
            "-i": FlagArgType.NONE,
            "--ignore-case": FlagArgType.NONE,
            "-v": FlagArgType.NONE,
            "--invert-match": FlagArgType.NONE,
            "-w": FlagArgType.NONE,
            "--word-regexp": FlagArgType.NONE,
            "-n": FlagArgType.NONE,
            "--line-number": FlagArgType.NONE,
            "-c": FlagArgType.NONE,
            "--count": FlagArgType.NONE,
            "-l": FlagArgType.NONE,
            "--files-with-matches": FlagArgType.NONE,
            "-L": FlagArgType.NONE,
            "--files-without-match": FlagArgType.NONE,
            "-h": FlagArgType.NONE,
            "-H": FlagArgType.NONE,
            "--heading": FlagArgType.NONE,
            "--break": FlagArgType.NONE,
            "--full-name": FlagArgType.NONE,
            "--color": FlagArgType.NONE,
            "--no-color": FlagArgType.NONE,
            "-o": FlagArgType.NONE,
            "--only-matching": FlagArgType.NONE,
            "-A": FlagArgType.NUMBER,
            "--after-context": FlagArgType.NUMBER,
            "-B": FlagArgType.NUMBER,
            "--before-context": FlagArgType.NUMBER,
            "-C": FlagArgType.NUMBER,
            "--context": FlagArgType.NUMBER,
            "--and": FlagArgType.NONE,
            "--or": FlagArgType.NONE,
            "--not": FlagArgType.NONE,
            "--max-depth": FlagArgType.NUMBER,
            "--untracked": FlagArgType.NONE,
            "--no-index": FlagArgType.NONE,
            "--recurse-submodules": FlagArgType.NONE,
            "--cached": FlagArgType.NONE,
            "--threads": FlagArgType.NUMBER,
            "-q": FlagArgType.NONE,
            "--quiet": FlagArgType.NONE,
        },
    ),
    "reflog": SubcommandConfig(
        safe_flags={
            **LOG_DISPLAY,
            **REF_SELECTION,
            **DATE_FILTER,
            **COUNT,
            **AUTHOR_FILTER,
        },
        is_positional_dangerous=reflog_positional_dangerous,
    ),
    "stash list": SubcommandConfig(
        safe_flags={
            **LOG_DISPLAY,
            **REF_SELECTION,
            **COUNT,
        },
    ),
    "stash show": SubcommandConfig(
        safe_flags={
            **STAT,
            **COLOR,
            **PATCH,
            "--word-diff": FlagArgType.NONE,
            "--word-diff-regex": FlagArgType.STRING,
            "--diff-filter": FlagArgType.STRING,
            "--abbrev": FlagArgType.NUMBER,
        },
    ),
    "worktree list": SubcommandConfig(
        safe_flags={
            "--porcelain": FlagArgType.NONE,
            "-v": FlagArgType.NONE,
            "--verbose": FlagArgType.NONE,
            "--expire": FlagArgType.STRING,
        },
    ),
    "remote show": SubcommandConfig(
        safe_flags={
            "-n": FlagArgType.NONE,
        },
        is_positional_dangerous=remote_show_positional_dangerous,
    ),
    "remote": SubcommandConfig(
        safe_flags={
            "-v": FlagArgType.NONE,
            "--verbose": FlagArgType.NONE,
        },
        is_positional_dangerous=remote_positional_dangerous,
    ),
    "tag": SubcommandConfig(
        safe_flags={
            "-l": FlagArgType.NONE,
            "--list": FlagArgType.NONE,
            "-n": FlagArgType.NUMBER,
            "--contains": FlagArgType.STRING,
            "--no-contains": FlagArgType.STRING,
            "--merged": FlagArgType.STRING,
            "--no-merged": FlagArgType.STRING,
            "--sort": FlagArgType.STRING,
            "--format": FlagArgType.STRING,
            "--points-at": FlagArgType.STRING,
            "--column": FlagArgType.NONE,
            "--no-column": FlagArgType.NONE,
            "-i": FlagArgType.NONE,
            "--ignore-case": FlagArgType.NONE,
        },
        is_positional_dangerous=tag_positional_dangerous,
    ),
    "branch": SubcommandConfig(
        safe_flags={
            "-l": FlagArgType.NONE,
            "--list": FlagArgType.NONE,
            "-a": FlagArgType.NONE,
            "--all": FlagArgType.NONE,
            "-r": FlagArgType.NONE,
            "--remotes": FlagArgType.NONE,
            "-v": FlagArgType.NONE,
            "-vv": FlagArgType.NONE,
            "--verbose": FlagArgType.NONE,
            "--color": FlagArgType.NONE,
            "--no-color": FlagArgType.NONE,
            "--column": FlagArgType.NONE,
            "--no-column": FlagArgType.NONE,
            "--abbrev": FlagArgType.NUMBER,
            "--no-abbrev": FlagArgType.NONE,
            "--contains": FlagArgType.STRING,
            "--no-contains": FlagArgType.STRING,
            "--merged": FlagArgType.NONE,
            "--no-merged": FlagArgType.NONE,
            "--points-at": FlagArgType.STRING,
            "--sort": FlagArgType.STRING,
            "--show-current": FlagArgType.NONE,
            "-i": FlagArgType.NONE,
            "--ignore-case": FlagArgType.NONE,
        },
        is_positional_dangerous=branch_positional_dangerous,
    ),
    "ls-remote": SubcommandConfig(
        safe_flags={
            "--branches": FlagArgType.NONE,
            "-b": FlagArgType.NONE,
            "--tags": FlagArgType.NONE,
            "-t": FlagArgType.NONE,
            "--heads": FlagArgType.NONE,
            "-h": FlagArgType.NONE,
            "--refs": FlagArgType.NONE,
            "--quiet": FlagArgType.NONE,
            "-q": FlagArgType.NONE,
            "--exit-code": FlagArgType.NONE,
            "--get-url": FlagArgType.NONE,
            "--symref": FlagArgType.NONE,
            "--sort": FlagArgType.STRING,
        },
    ),
    "config --get": SubcommandConfig(
        safe_flags={
            "--local": FlagArgType.NONE,
            "--global": FlagArgType.NONE,
            "--system": FlagArgType.NONE,
            "--worktree": FlagArgType.NONE,
            "--default": FlagArgType.STRING,
            "--type": FlagArgType.STRING,
            "--bool": FlagArgType.NONE,
            "--int": FlagArgType.NONE,
            "--bool-or-int": FlagArgType.NONE,
            "--path": FlagArgType.NONE,
            "--expiry-date": FlagArgType.NONE,
            "-z": FlagArgType.NONE,
            "--null": FlagArgType.NONE,
            "--name-only": FlagArgType.NONE,
            "--show-origin": FlagArgType.NONE,
            "--show-scope": FlagArgType.NONE,
        },
    ),
}
