"""Rust ecosystem safe subcommand configurations (cargo).

Includes read-only subcommands and workspace-safe build/check operations.

[INPUT]
- (none)

[OUTPUT]
- (none)

[POS]
Rust ecosystem safe subcommand configurations (cargo).
"""

from __future__ import annotations

from myrm_agent_harness.toolkits.code_execution.security.safe_command_configs.types import (
    FlagArgType,
    SubcommandConfig,
)

CARGO_SAFE_SUBCOMMANDS: dict[str, SubcommandConfig] = {
    "tree": SubcommandConfig(
        safe_flags={
            "--all-features": FlagArgType.NONE,
            "--no-default-features": FlagArgType.NONE,
            "--features": FlagArgType.STRING,
            "-F": FlagArgType.STRING,
            "--depth": FlagArgType.NUMBER,
            "--invert": FlagArgType.NONE,
            "-i": FlagArgType.NONE,
            "--duplicates": FlagArgType.NONE,
            "-d": FlagArgType.NONE,
            "--target": FlagArgType.STRING,
            "--edges": FlagArgType.STRING,
            "-e": FlagArgType.STRING,
            "--prefix": FlagArgType.STRING,
            "--format": FlagArgType.STRING,
            "-f": FlagArgType.STRING,
            "--package": FlagArgType.STRING,
            "-p": FlagArgType.STRING,
            "--workspace": FlagArgType.NONE,
            "--manifest-path": FlagArgType.STRING,
        },
    ),
    "metadata": SubcommandConfig(
        safe_flags={
            "--format-version": FlagArgType.NUMBER,
            "--no-deps": FlagArgType.NONE,
            "--all-features": FlagArgType.NONE,
            "--no-default-features": FlagArgType.NONE,
            "--features": FlagArgType.STRING,
            "-F": FlagArgType.STRING,
            "--filter-platform": FlagArgType.STRING,
            "--manifest-path": FlagArgType.STRING,
        },
    ),
    "pkgid": SubcommandConfig(
        safe_flags={
            "--manifest-path": FlagArgType.STRING,
            "--package": FlagArgType.STRING,
            "-p": FlagArgType.STRING,
        },
    ),
    "check": SubcommandConfig(
        safe_flags={
            "--all-features": FlagArgType.NONE,
            "--no-default-features": FlagArgType.NONE,
            "--features": FlagArgType.STRING,
            "-F": FlagArgType.STRING,
            "--all-targets": FlagArgType.NONE,
            "--lib": FlagArgType.NONE,
            "--bins": FlagArgType.NONE,
            "--tests": FlagArgType.NONE,
            "--benches": FlagArgType.NONE,
            "--examples": FlagArgType.NONE,
            "--workspace": FlagArgType.NONE,
            "--package": FlagArgType.STRING,
            "-p": FlagArgType.STRING,
            "--target": FlagArgType.STRING,
            "--release": FlagArgType.NONE,
            "--profile": FlagArgType.STRING,
            "--jobs": FlagArgType.NUMBER,
            "-j": FlagArgType.NUMBER,
            "--verbose": FlagArgType.NONE,
            "-v": FlagArgType.NONE,
            "--quiet": FlagArgType.NONE,
            "-q": FlagArgType.NONE,
            "--message-format": FlagArgType.STRING,
            "--manifest-path": FlagArgType.STRING,
        },
    ),
    "clippy": SubcommandConfig(
        safe_flags={
            "--all-features": FlagArgType.NONE,
            "--no-default-features": FlagArgType.NONE,
            "--features": FlagArgType.STRING,
            "-F": FlagArgType.STRING,
            "--all-targets": FlagArgType.NONE,
            "--lib": FlagArgType.NONE,
            "--bins": FlagArgType.NONE,
            "--tests": FlagArgType.NONE,
            "--benches": FlagArgType.NONE,
            "--examples": FlagArgType.NONE,
            "--workspace": FlagArgType.NONE,
            "--package": FlagArgType.STRING,
            "-p": FlagArgType.STRING,
            "--target": FlagArgType.STRING,
            "--release": FlagArgType.NONE,
            "--profile": FlagArgType.STRING,
            "--jobs": FlagArgType.NUMBER,
            "-j": FlagArgType.NUMBER,
            "--verbose": FlagArgType.NONE,
            "-v": FlagArgType.NONE,
            "--quiet": FlagArgType.NONE,
            "-q": FlagArgType.NONE,
            "--message-format": FlagArgType.STRING,
            "--manifest-path": FlagArgType.STRING,
        },
    ),
    "build": SubcommandConfig(
        safe_flags={
            "--all-features": FlagArgType.NONE,
            "--no-default-features": FlagArgType.NONE,
            "--features": FlagArgType.STRING,
            "-F": FlagArgType.STRING,
            "--all-targets": FlagArgType.NONE,
            "--lib": FlagArgType.NONE,
            "--bins": FlagArgType.NONE,
            "--tests": FlagArgType.NONE,
            "--benches": FlagArgType.NONE,
            "--examples": FlagArgType.NONE,
            "--workspace": FlagArgType.NONE,
            "--package": FlagArgType.STRING,
            "-p": FlagArgType.STRING,
            "--target": FlagArgType.STRING,
            "--release": FlagArgType.NONE,
            "--profile": FlagArgType.STRING,
            "--jobs": FlagArgType.NUMBER,
            "-j": FlagArgType.NUMBER,
            "--verbose": FlagArgType.NONE,
            "-v": FlagArgType.NONE,
            "--quiet": FlagArgType.NONE,
            "-q": FlagArgType.NONE,
            "--message-format": FlagArgType.STRING,
            "--manifest-path": FlagArgType.STRING,
        },
    ),
    "test": SubcommandConfig(
        safe_flags={
            "--all-features": FlagArgType.NONE,
            "--no-default-features": FlagArgType.NONE,
            "--features": FlagArgType.STRING,
            "-F": FlagArgType.STRING,
            "--all-targets": FlagArgType.NONE,
            "--lib": FlagArgType.NONE,
            "--bins": FlagArgType.NONE,
            "--tests": FlagArgType.NONE,
            "--benches": FlagArgType.NONE,
            "--examples": FlagArgType.NONE,
            "--doc": FlagArgType.NONE,
            "--workspace": FlagArgType.NONE,
            "--package": FlagArgType.STRING,
            "-p": FlagArgType.STRING,
            "--target": FlagArgType.STRING,
            "--release": FlagArgType.NONE,
            "--profile": FlagArgType.STRING,
            "--jobs": FlagArgType.NUMBER,
            "-j": FlagArgType.NUMBER,
            "--verbose": FlagArgType.NONE,
            "-v": FlagArgType.NONE,
            "--quiet": FlagArgType.NONE,
            "-q": FlagArgType.NONE,
            "--message-format": FlagArgType.STRING,
            "--no-run": FlagArgType.NONE,
            "--no-fail-fast": FlagArgType.NONE,
            "--manifest-path": FlagArgType.STRING,
        },
    ),
    "doc": SubcommandConfig(
        safe_flags={
            "--all-features": FlagArgType.NONE,
            "--no-default-features": FlagArgType.NONE,
            "--features": FlagArgType.STRING,
            "-F": FlagArgType.STRING,
            "--workspace": FlagArgType.NONE,
            "--package": FlagArgType.STRING,
            "-p": FlagArgType.STRING,
            "--no-deps": FlagArgType.NONE,
            "--document-private-items": FlagArgType.NONE,
            "--target": FlagArgType.STRING,
            "--release": FlagArgType.NONE,
            "--profile": FlagArgType.STRING,
            "--jobs": FlagArgType.NUMBER,
            "-j": FlagArgType.NUMBER,
            "--verbose": FlagArgType.NONE,
            "-v": FlagArgType.NONE,
            "--quiet": FlagArgType.NONE,
            "-q": FlagArgType.NONE,
            "--manifest-path": FlagArgType.STRING,
        },
    ),
    "version": SubcommandConfig(
        safe_flags={
            "--verbose": FlagArgType.NONE,
            "-v": FlagArgType.NONE,
        },
    ),
}
