"""Compaction State Preservation Guard enforcing zero-loss task state retention."""

from .models import CompactionAnchorPayload
from .tracker import StructuredTaskStateTracker


class CompactionStatePreservationGuard:
    """Interception guard ensuring structured task states survive rolling context summarization."""

    def __init__(self, tracker: StructuredTaskStateTracker) -> None:
        """Initialize preservation guard with underlying task tracker.

        Args:
            tracker: Authoritative structured task state tracker.
        """
        self._tracker = tracker

    def apply_compaction_anchor(
        self,
        session_id: str,
        raw_summary: str,
    ) -> CompactionAnchorPayload:
        """Extract structured task state and construct an immutable compound compaction payload.

        Args:
            session_id: Active session identifier.
            raw_summary: Natural language rolling summary generated by compaction engine.

        Returns:
            CompactionAnchorPayload combining natural language summary and structured state.

        Raises:
            KeyError: If session has no tracked task state.
        """
        state = self._tracker.get_state(session_id)
        if state is None:
            raise KeyError(f"Cannot compact: no structured task state tracked for session '{session_id}'.")

        anchor_text = self._tracker.render_compaction_anchor(session_id)

        # Monotonically bump state version during compaction cycle to mark survival milestone
        state.version += 1

        return CompactionAnchorPayload(
            session_id=session_id,
            raw_summary=raw_summary,
            structured_state=state.model_copy(deep=True),
            anchor_text=anchor_text,
        )

    def assemble_compacted_context(
        self,
        session_id: str,
        raw_summary: str,
    ) -> str:
        """Render high-priority prompt segment positioning the structured anchor atop the summary.

        Args:
            session_id: Active session identifier.
            raw_summary: Textual compressed dialogue history.

        Returns:
            Complete composite context block ready for system prompt injection.
        """
        payload = self.apply_compaction_anchor(session_id, raw_summary)
        sections = [
            payload.anchor_text,
            "\n### [DIALOGUE ROLLING SUMMARY]",
            payload.raw_summary.strip(),
        ]
        return "\n".join(sections)
