"""File filtering rules for artifact collection.

This module provides rules to filter out:
1. System/temporary files (e.g., .DS_Store, *.pyc)
2. Skill resource files (e.g., .claude/skills/*)

[INPUT]
- (none)

[OUTPUT]
- should_ignore_artifact: Check if a file should be ignored during artifact collect...
- should_filter_skill_resource: Check if a file is a skill resource that should be filter...

[POS]
File filtering rules for artifact collection.
"""

from pathlib import Path

# Artifact collection ignore patterns
# These are temporary/system files generated by the sandbox executor
IGNORED_ARTIFACT_PATTERNS: list[str] = [
    "_metadata.json",
    ".DS_Store",
    "__pycache__",
    "*.pyc",
    ".git",
    ".gitignore",
    "run.py",  # wrapper script
    "user_code.py",  # temporary user code file
]


def should_ignore_artifact(filename: str) -> bool:
    """Check if file should be ignored (not collected as artifact).

    Checks against system/temporary file patterns.

    Args:
        filename: Filename only (no path)

    Returns:
        True if file should be ignored

    Example:
        >>> should_ignore_artifact("output.txt")
        False
        >>> should_ignore_artifact(".DS_Store")
        True
        >>> should_ignore_artifact("test.pyc")
        True
    """
    for pattern in IGNORED_ARTIFACT_PATTERNS:
        if pattern.startswith("*"):
            if filename.endswith(pattern[1:]):
                return True
        elif filename == pattern:
            return True
    return False


def should_filter_skill_resource(relative_path: str | Path) -> bool:
    """Check if file is a skill resource (should be filtered).

    Design Principle:
    ---------------------
    The `.claude/skills/` directory should be treated as a "tool/library"
    (similar to node_modules, .venv), where files are system resources,
    not user-generated outputs.

    Problem Context:
    ---------------------
    - Skills are copied to workspace `.claude/skills/` on first use
    - Copy operation happens before command execution, so mtime is recent
    - Time-based artifact collection incorrectly treats skill data files
      (e.g., data/*.csv) as artifacts

    Output Convention:
    ---------------------
    - Skill output files should be generated in the main workspace area
      (e.g., root directory, output/)
    - Users should not need to look in hidden system directories for output
    - If a skill generates files in its own directory, that's a skill design
      issue and should be fixed in the skill itself

    Args:
        relative_path: Path relative to workspace root

    Returns:
        True if file is a skill resource and should be filtered

    Example:
        >>> should_filter_skill_resource(".claude/skills/ui-ux-pro-max/data/colors.csv")
        True
        >>> should_filter_skill_resource(".claude/skills/pptx/scripts/main.py")
        True
        >>> should_filter_skill_resource("output.html")
        False
        >>> should_filter_skill_resource("my-skill/output.pdf")
        False
    """
    path_parts = Path(relative_path).parts
    # Filter all files under .claude/skills/
    return len(path_parts) >= 2 and path_parts[0] == ".claude" and path_parts[1] == "skills"
