"""Pluggable memory system for AI agents.

Protocol-first design: the framework defines only interfaces (Protocols)
and orchestration logic. Concrete storage backends are provided by the
application layer via dependency injection.
"""

from myrm_agent_harness.toolkits.memory._internal.embedding_cache import EmbeddingCache
from myrm_agent_harness.toolkits.memory._internal.memory_scanner import ScanMetricsSnapshot, get_scan_metrics
from myrm_agent_harness.toolkits.memory._internal.storage import MemoryError, MemoryNotFoundError
from myrm_agent_harness.toolkits.memory.config import (
    AgentMemoryPolicy,
    ConsolidationConfig,
    MemoryConfig,
    MemoryScopeLevel,
    MemoryWritePolicy,
    RecallMode,
    RetrievalConfig,
)
from myrm_agent_harness.toolkits.memory.conversation_search import (
    CONVERSATION_SEARCH_TOOL_NAME,
    ConversationSearchHit,
    ConversationSearchRequest,
    ConversationSearchResponse,
    MemoryConversationSearchProvider,
    create_conversation_search_tool,
)
from myrm_agent_harness.toolkits.memory.health import HealthScore, MaintenanceReport, MemorySnapshot, NeglectedMemory
from myrm_agent_harness.toolkits.memory.manager import MemoryManager
from myrm_agent_harness.toolkits.memory.metrics import SearchMetrics, SearchSnapshot, get_search_metrics
from myrm_agent_harness.toolkits.memory.observability import (
    MemoryInfluenceRef,
    MemoryOperationEvent,
    MemoryOperationKind,
    MemoryOperationSink,
    MemoryOperationStatus,
    MemoryRetrievalTrace,
    MemorySpaceBinding,
    MemorySpaceKind,
    MemoryTraceStep,
    ScalarValue,
)
from myrm_agent_harness.toolkits.memory.protocols import (
    ConversationSearchProtocol,
    EmbeddingCacheProtocol,
    EmbeddingProtocol,
    GraphStoreProtocol,
    RelationalStoreProtocol,
    VectorStoreProtocol,
)
from myrm_agent_harness.toolkits.memory.reliability import (
    MemoryArchiveDryRunResult,
    MemoryArchiveManifest,
    MemoryArchivePayload,
    MemoryArchiveRestoreDryRunResult,
    MemoryArchiveRestoreItemStatus,
    MemoryArchiveRestoreMode,
    MemoryArchiveRestoreMutationRef,
    MemoryArchiveRestorePlan,
    MemoryArchiveRestoreResult,
    MemoryArchiveRestoreRollbackPreview,
    MemoryArchiveRestoreRollbackResult,
    MemoryArchiveRestoreSectionPlan,
    MemoryArchiveRestoreSecurityFinding,
    MemoryArchiveRestoreSecurityVerdict,
    MemoryArchiveRestoreStatus,
    MemoryArchiveSection,
    MemoryArchiveSectionName,
    MemoryArchiveSectionStatus,
    MemoryImportDryRunResult,
    MemoryImportDryRunSummary,
    MemoryImportMappingItem,
    MemoryImportMappingStatus,
    MemoryImportPlan,
    MemoryImportPlanItem,
    MemoryImportSource,
    MemoryRecallBenchmarkCase,
    MemoryRecallBenchmarkResult,
    MemoryRecallBenchmarkSummary,
    MemoryReliabilityCategory,
    MemoryReliabilityProbeResult,
    MemoryReliabilityStatus,
    MemoryRepairExecutionResult,
    MemoryRepairExecutionStatus,
    MemoryRepairPlan,
    MemoryRepairRiskLevel,
    summarize_recall_benchmark,
)
from myrm_agent_harness.toolkits.memory.retriever import MemoryRetriever
from myrm_agent_harness.toolkits.memory.session import MemorySession
from myrm_agent_harness.toolkits.memory.setup import create_local_memory_manager
from myrm_agent_harness.toolkits.memory.signals import SignalCalculator
from myrm_agent_harness.toolkits.memory.strategies import (
    ExtractedMemory,
    ExtractionConfig,
    ExtractionResult,
    ForgettingConfig,
    ForgettingResult,
    ForgettingStrategy,
    MemoryExtractor,
    RetentionScore,
    extract_memories_from_conversation,
)
from myrm_agent_harness.toolkits.memory.tool_capture import ToolMemoryCaptureHook
from myrm_agent_harness.toolkits.memory.types import (
    AnyMemory,
    BaseMemory,
    EpisodicMemory,
    EpisodicRelation,
    MemoryMutationRef,
    MemoryMutationResult,
    MemorySearchResult,
    MemoryStatus,
    MemoryType,
    PendingRecord,
    ProceduralMemory,
    ProfileAttributeSnapshot,
    ProfileEntry,
    RuleSource,
    SemanticMemory,
    ToolRulePriority,
)

__all__ = [
    "CONVERSATION_SEARCH_TOOL_NAME",
    "AgentMemoryPolicy",
    "AnyMemory",
    "BaseMemory",
    "ConsolidationConfig",
    "ConversationSearchHit",
    "ConversationSearchProtocol",
    "ConversationSearchRequest",
    "ConversationSearchResponse",
    "EmbeddingCache",
    "EmbeddingCacheProtocol",
    "EmbeddingProtocol",
    "EpisodicMemory",
    "EpisodicRelation",
    "ExtractedMemory",
    "ExtractionConfig",
    "ExtractionResult",
    "ForgettingConfig",
    "ForgettingResult",
    "ForgettingStrategy",
    "GraphStoreProtocol",
    "HealthScore",
    "MaintenanceReport",
    "MemoryArchiveDryRunResult",
    "MemoryArchiveManifest",
    "MemoryArchivePayload",
    "MemoryArchiveRestoreDryRunResult",
    "MemoryArchiveRestoreItemStatus",
    "MemoryArchiveRestoreMode",
    "MemoryArchiveRestoreMutationRef",
    "MemoryArchiveRestorePlan",
    "MemoryArchiveRestoreResult",
    "MemoryArchiveRestoreRollbackPreview",
    "MemoryArchiveRestoreRollbackResult",
    "MemoryArchiveRestoreSectionPlan",
    "MemoryArchiveRestoreSecurityFinding",
    "MemoryArchiveRestoreSecurityVerdict",
    "MemoryArchiveRestoreStatus",
    "MemoryArchiveSection",
    "MemoryArchiveSectionName",
    "MemoryArchiveSectionStatus",
    "MemoryConfig",
    "MemoryConversationSearchProvider",
    "MemoryError",
    "MemoryExtractor",
    "MemoryImportDryRunResult",
    "MemoryImportDryRunSummary",
    "MemoryImportMappingItem",
    "MemoryImportMappingStatus",
    "MemoryImportPlan",
    "MemoryImportPlanItem",
    "MemoryImportSource",
    "MemoryInfluenceRef",
    "MemoryManager",
    "MemoryMutationRef",
    "MemoryMutationResult",
    "MemoryNotFoundError",
    "MemoryOperationEvent",
    "MemoryOperationKind",
    "MemoryOperationSink",
    "MemoryOperationStatus",
    "MemoryRecallBenchmarkCase",
    "MemoryRecallBenchmarkResult",
    "MemoryRecallBenchmarkSummary",
    "MemoryReliabilityCategory",
    "MemoryReliabilityProbeResult",
    "MemoryReliabilityStatus",
    "MemoryRepairExecutionResult",
    "MemoryRepairExecutionStatus",
    "MemoryRepairPlan",
    "MemoryRepairRiskLevel",
    "MemoryRetrievalTrace",
    "MemoryRetriever",
    "MemoryScopeLevel",
    "MemorySearchResult",
    "MemorySession",
    "MemorySnapshot",
    "MemorySpaceBinding",
    "MemorySpaceKind",
    "MemoryStatus",
    "MemoryTraceStep",
    "MemoryType",
    "MemoryWritePolicy",
    "NeglectedMemory",
    "PendingRecord",
    "ProceduralMemory",
    "ProfileAttributeSnapshot",
    "ProfileEntry",
    "RecallMode",
    "RelationalStoreProtocol",
    "RetentionScore",
    "RetrievalConfig",
    "RuleSource",
    "ScalarValue",
    "ScanMetricsSnapshot",
    "SearchMetrics",
    "SearchSnapshot",
    "SemanticMemory",
    "SignalCalculator",
    "ToolMemoryCaptureHook",
    "ToolRulePriority",
    "VectorStoreProtocol",
    "create_conversation_search_tool",
    "create_local_memory_manager",
    "extract_memories_from_conversation",
    "get_scan_metrics",
    "get_search_metrics",
    "summarize_recall_benchmark",
]
