"""Approval Audit and Multi-Dimensional Quota Attribution Type Definitions.

[INPUT]
- None (Standard library dataclasses, enum, datetime, typing)

[OUTPUT]
- ApprovalTriggerCategory: Standard 4-category classification of approval triggers
- ApprovalTriggerEvent: Immutable single trigger event record
- TopOffenderItem: Aggregated frequent trigger target with suggested allowlist pattern
- DualTrackQuotaBreakdown: Decoupled consumption metrics (Main Task vs Auto-Review Audit Agent)
- AutoApprovalAuditReport: Complete aggregated diagnostic report for session or fleet

[POS]
Type definitions and data contracts for auto-approval root cause diagnostics,
top-offenders ranking, and multi-dimensional quota attribution.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import StrEnum
from typing import Mapping


class ApprovalTriggerCategory(StrEnum):
    """Four-category classification of auto-approval trigger causes."""

    FILE_BOUNDARY = "FILE_BOUNDARY"          # Writing/reading outside workspace boundary
    NETWORK_DOMAIN = "NETWORK_DOMAIN"        # Accessing non-whitelisted external URLs/domains
    COMMAND_EXECUTION = "COMMAND_EXECUTION"  # Executing unapproved shell commands/binaries
    TOOL_ELEVATION = "TOOL_ELEVATION"        # High-risk tool or MCP privilege elevation
    UNKNOWN = "UNKNOWN"                      # Fallback / unclassified trigger


@dataclass(frozen=True, slots=True)
class ApprovalTriggerEvent:
    """Immutable single approval trigger record.

    Attributes:
        trigger_id: Unique event identifier.
        session_id: Associated chat or task session ID.
        category: Classified ApprovalTriggerCategory.
        raw_target: Original raw parameter (e.g. full path, url, command line).
        normalized_target: Normalized target (e.g. dir prefix, domain host, command basename).
        tool_name: Tool that triggered the approval check.
        prompt_tokens: Input tokens consumed for this approval check/turn.
        completion_tokens: Output tokens generated by the reviewer.
        cost_usd: Estimated cost in USD for this trigger.
        is_audit_agent: Whether this event was incurred by an auxiliary auto-review agent.
        occurred_at: Event timestamp.
    """

    session_id: str
    category: ApprovalTriggerCategory
    raw_target: str
    normalized_target: str
    tool_name: str
    prompt_tokens: int = 0
    completion_tokens: int = 0
    cost_usd: float = 0.0
    is_audit_agent: bool = False
    trigger_id: str = field(default_factory=lambda: uuid.uuid4().hex)
    occurred_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def total_tokens(self) -> int:
        """Total tokens for this trigger event."""
        return self.prompt_tokens + self.completion_tokens


@dataclass(frozen=True, slots=True)
class TopOffenderItem:
    """Aggregated frequently intercepted target with recommended allowlist pattern.

    Attributes:
        normalized_target: Normalized cluster key (e.g. 'api.github.com', '/var/log/*').
        category: Trigger category.
        hit_count: Number of times this target triggered approval.
        total_tokens: Total tokens consumed across all hits.
        estimated_cost_usd: Total estimated cost in USD across all hits.
        suggested_allow_pattern: Actionable pattern for project allowlist.
    """

    normalized_target: str
    category: ApprovalTriggerCategory
    hit_count: int
    total_tokens: int
    estimated_cost_usd: float
    suggested_allow_pattern: str


@dataclass(frozen=True, slots=True)
class DualTrackQuotaBreakdown:
    """Decoupled usage metrics separating main task execution from auxiliary security review.

    Attributes:
        main_task_rounds: Turn count executed by primary task model.
        main_task_prompt_tokens: Input tokens used by primary model.
        main_task_completion_tokens: Output tokens generated by primary model.
        main_task_cost_usd: Cost in USD of primary model execution.
        audit_agent_rounds: Turn count executed by auto-approval / security reviewer.
        audit_agent_prompt_tokens: Input tokens consumed by reviewer agent.
        audit_agent_completion_tokens: Output tokens generated by reviewer agent.
        audit_agent_cost_usd: Cost in USD of reviewer agent.
    """

    main_task_rounds: int = 0
    main_task_prompt_tokens: int = 0
    main_task_completion_tokens: int = 0
    main_task_cost_usd: float = 0.0
    audit_agent_rounds: int = 0
    audit_agent_prompt_tokens: int = 0
    audit_agent_completion_tokens: int = 0
    audit_agent_cost_usd: float = 0.0

    @property
    def main_task_total_tokens(self) -> int:
        return self.main_task_prompt_tokens + self.main_task_completion_tokens

    @property
    def audit_agent_total_tokens(self) -> int:
        return self.audit_agent_prompt_tokens + self.audit_agent_completion_tokens

    @property
    def audit_rounds(self) -> int:
        return self.audit_agent_rounds

    @property
    def audit_prompt_tokens(self) -> int:
        return self.audit_agent_prompt_tokens

    @property
    def audit_completion_tokens(self) -> int:
        return self.audit_agent_completion_tokens

    @property
    def audit_cost_usd(self) -> float:
        return self.audit_agent_cost_usd

    @property
    def audit_token_ratio(self) -> float:
        if self.total_tokens <= 0:
            return 0.0
        return min(1.0, round(self.audit_agent_total_tokens / self.total_tokens, 4))

    @property
    def total_rounds(self) -> int:
        return self.main_task_rounds + self.audit_agent_rounds

    @property
    def total_tokens(self) -> int:
        return self.main_task_total_tokens + self.audit_agent_total_tokens

    @property
    def total_cost_usd(self) -> float:
        return round(self.main_task_cost_usd + self.audit_agent_cost_usd, 6)

    @property
    def audit_cost_ratio(self) -> float:
        """Percentage of total cost spent on security approval review (0.0 to 1.0)."""
        if self.total_cost_usd <= 0.0:
            return 0.0
        return min(1.0, round(self.audit_agent_cost_usd / self.total_cost_usd, 4))


@dataclass(frozen=True, slots=True)
class AutoApprovalAuditReport:
    """Comprehensive diagnostic report summarizing trigger causes and attribution.

    Attributes:
        session_id: Session identifier.
        total_triggers: Total approval trigger events recorded.
        category_counts: Map of category to trigger frequency.
        dual_track_breakdown: Split of main task vs audit agent consumption.
        top_offenders: Ranked list of top frequently intercepted targets.
        recommendations: Actionable governance recommendations for user/admin.
    """

    session_id: str
    total_triggers: int
    category_counts: Mapping[ApprovalTriggerCategory, int]
    dual_track_breakdown: DualTrackQuotaBreakdown
    top_offenders: list[TopOffenderItem] = field(default_factory=list)
    recommendations: list[str] = field(default_factory=list)
