"""Auto-Approval Trigger Diagnostics and Multi-Dimensional Quota Attribution Type Contracts.

[INPUT]
- None (Standard library dataclasses, enum, datetime, typing)

[OUTPUT]
- ApprovalTriggerCategory: Standard 4-category classification enum (FILE, NETWORK, COMMAND, TOOL, UNKNOWN)
- ApprovalTriggerEvent: Immutable single auto-approval or security intervention event
- TopOffenderItem: Aggregated high-frequency boundary violation target with suggested allow pattern
- DualTrackQuotaBreakdown: Decoupled accounting for main task model vs security reviewer agent
- AutoApprovalAuditReport: Comprehensive session/fleet diagnostic and attribution report

[POS]
Harness-level observability type system for auto-approval root-cause diagnostics, dual-track quota separation, and least-privilege rule suggestion.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import StrEnum
from typing import Mapping, Sequence


class ApprovalTriggerCategory(StrEnum):
    """Standard 4-category taxonomy for auto-approval and security interventions."""

    FILE_BOUNDARY = "FILE_BOUNDARY"        # Out-of-workspace or restricted path access
    NETWORK_DOMAIN = "NETWORK_DOMAIN"      # Non-allowlisted external domain / URL access
    COMMAND_EXECUTION = "COMMAND_EXECUTION"  # Destructive shell command or compilation invocation
    TOOL_ELEVATION = "TOOL_ELEVATION"      # High-risk tool / MCP privilege escalation
    UNKNOWN = "UNKNOWN"                    # Unclassified or generic fallback


@dataclass(frozen=True, slots=True)
class ApprovalTriggerEvent:
    """Individual record of a security review trigger or auto-approval event.

    Attributes:
        session_id: Session where the trigger occurred.
        category: Classified ApprovalTriggerCategory.
        raw_target: Raw parameter string (e.g. full path, url, shell command).
        normalized_target: Sanitized and clustered target (e.g. parent directory, host domain, command binary).
        tool_name: Associated tool name (e.g. 'bash_exec', 'web_fetch', 'file_write').
        prompt_tokens: Prompt tokens consumed during the security review / intervention.
        completion_tokens: Output tokens generated by the reviewer model.
        cached_prompt_tokens: Subset of prompt tokens served from cache.
        cost_usd: Estimated cost in USD for this review call.
        trigger_id: Unique event identifier.
        occurred_at: Event timestamp.
    """

    session_id: str
    category: ApprovalTriggerCategory
    raw_target: str
    normalized_target: str
    tool_name: str
    prompt_tokens: int = 0
    completion_tokens: int = 0
    cached_prompt_tokens: int = 0
    cost_usd: float = 0.0
    trigger_id: str = field(default_factory=lambda: uuid.uuid4().hex)
    occurred_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def total_tokens(self) -> int:
        """Total tokens consumed by this approval review event."""
        return self.prompt_tokens + self.completion_tokens


@dataclass(frozen=True, slots=True)
class TopOffenderItem:
    """High-frequency boundary violation target with actionable remediation hint.

    Attributes:
        normalized_target: Clustered target identifier (e.g. 'api.github.com', '/var/log/*').
        category: ApprovalTriggerCategory of the offender.
        hit_count: Number of times this target triggered auto-approval.
        total_tokens: Total tokens consumed by reviews on this target.
        estimated_cost_usd: Total estimated cost in USD.
        suggested_allow_pattern: Actionable least-privilege allowlist pattern.
    """

    normalized_target: str
    category: ApprovalTriggerCategory
    hit_count: int
    total_tokens: int
    estimated_cost_usd: float
    suggested_allow_pattern: str


@dataclass(frozen=True, slots=True)
class DualTrackQuotaBreakdown:
    """Decoupled quota and financial cost attribution across main task vs security audit.

    Attributes:
        main_task_rounds: Primary reasoning model call turns.
        main_task_input_tokens: Input tokens consumed by main model.
        main_task_output_tokens: Output tokens generated by main model.
        main_task_cached_tokens: Cached prompt tokens saved by main model.
        main_task_cost_usd: Financial cost incurred by main task.
        audit_reviewer_rounds: Auto-approval and security review agent call turns.
        audit_reviewer_input_tokens: Input tokens consumed by reviewer agent.
        audit_reviewer_output_tokens: Output tokens generated by reviewer agent.
        audit_reviewer_cached_tokens: Cached tokens saved by reviewer agent.
        audit_reviewer_cost_usd: Financial cost incurred by reviewer agent.
    """

    main_task_rounds: int = 0
    main_task_input_tokens: int = 0
    main_task_output_tokens: int = 0
    main_task_cached_tokens: int = 0
    main_task_cost_usd: float = 0.0

    audit_reviewer_rounds: int = 0
    audit_reviewer_input_tokens: int = 0
    audit_reviewer_output_tokens: int = 0
    audit_reviewer_cached_tokens: int = 0
    audit_reviewer_cost_usd: float = 0.0

    @property
    def total_rounds(self) -> int:
        """Total combined invocation rounds."""
        return self.main_task_rounds + self.audit_reviewer_rounds

    @property
    def total_tokens(self) -> int:
        """Total combined token consumption."""
        return (
            self.main_task_input_tokens
            + self.main_task_output_tokens
            + self.audit_reviewer_input_tokens
            + self.audit_reviewer_output_tokens
        )

    @property
    def total_cost_usd(self) -> float:
        """Total combined financial expenditure."""
        return round(self.main_task_cost_usd + self.audit_reviewer_cost_usd, 6)

    @property
    def audit_cost_ratio(self) -> float:
        """Ratio of security review cost against total expenditure (0.0 to 1.0)."""
        if self.total_cost_usd <= 0.0:
            return 0.0
        return min(1.0, round(self.audit_reviewer_cost_usd / self.total_cost_usd, 4))


@dataclass(frozen=True, slots=True)
class AutoApprovalAuditReport:
    """Comprehensive diagnostic and attribution report for auto-approvals.

    Attributes:
        session_id: Evaluated session identifier.
        total_triggers: Total number of review trigger events.
        category_counts: Distribution count per ApprovalTriggerCategory.
        dual_track_breakdown: Disaggregated usage across task vs review models.
        top_offenders: Ranked list of highest frequency triggers with allowlist suggestions.
        recommendations: Actionable policy suggestions to eliminate redundant review cycles.
    """

    session_id: str
    total_triggers: int
    category_counts: Mapping[str, int]
    dual_track_breakdown: DualTrackQuotaBreakdown
    top_offenders: Sequence[TopOffenderItem] = field(default_factory=list)
    recommendations: Sequence[str] = field(default_factory=list)
