"""Data schemas and contracts for Hebbian Fact Injection and Linear Memory Editing.

Defines high-priority FactPatch entities, projection results, and conflict probe reports
designed to override pre-trained model prior bias (inspired by Kimi KDA & Hebbian memory).

[INPUT]
- pydantic::BaseModel, Field, field_validator (POS: schema definition and validation)
- datetime, uuid (POS: timestamping and identity generation)

[OUTPUT]
- FactPatch: High-priority factual override patch with anti-bias suppression patterns.
- PatchMatchResult: Injection payload synthesized for prompt attention modulation.
- ConflictProbeReport: Diagnostic result from adversarial probe testing fact overriding.

[POS]
Foundational contracts for direct fact editing and pre-trained prior bias elimination.
"""

from __future__ import annotations

from datetime import UTC, datetime
from uuid import uuid4

from pydantic import BaseModel, Field, field_validator


def _utc_now() -> datetime:
    return datetime.now(UTC)


class FactPatch(BaseModel):
    """High-priority factual override patch equipped with anti-bias suppression patterns.

    Directly overrides deep pre-trained prior biases (e.g. insisting on 'master' branch or 'mysql' db)
    by projecting non-negotiable factual constraints into prompt attention space.
    """

    patch_id: str = Field(default_factory=lambda: f"patch_{uuid4().hex[:12]}")
    entity: str = Field(..., description="Target entity identifier (e.g. 'default_branch', 'database')")
    attribute: str = Field(..., description="Target property name (e.g. 'branch_name', 'engine')")
    override_value: str = Field(..., description="Strict user-specified override value (e.g. 'main', 'postgres')")
    statement: str = Field(
        ...,
        description="Declarative non-negotiable instruction overriding prior habit",
    )
    anti_bias_patterns: list[str] = Field(
        default_factory=list,
        description="Specific obsolete/pre-trained patterns to strictly suppress (e.g. ['master', 'origin/master'])",
    )
    scope_id: str = Field(default="default", description="Workspace or namespace scope")
    priority_weight: float = Field(
        default=1.0,
        ge=0.5,
        le=2.0,
        description="Attention priority multiplier (default 1.0 is maximum hard constraint)",
    )
    is_active: bool = Field(default=True, description="Whether this patch is actively enforced")
    created_at: datetime = Field(default_factory=_utc_now)
    updated_at: datetime = Field(default_factory=_utc_now)

    @field_validator("created_at", "updated_at", mode="before")
    @classmethod
    def _ensure_utc(cls, v: datetime | str | None) -> datetime:
        if v is None:
            return _utc_now()
        if isinstance(v, str):
            v = datetime.fromisoformat(v)
        if v.tzinfo is None:
            return v.replace(tzinfo=UTC)
        return v


class PatchMatchResult(BaseModel):
    """Result of matching and synthesizing active fact patches for prompt attention injection."""

    matched_patches: list[FactPatch] = Field(default_factory=list)
    suppressed_bias_tokens: list[str] = Field(default_factory=list)
    injection_prompt: str = Field(
        default="",
        description="Synthesized high-priority guardrail prompt forcing compliance",
    )


class ConflictProbeReport(BaseModel):
    """Adversarial diagnostic audit verifying that new fact 100% suppresses legacy prior bias."""

    patch_id: str
    probed_query: str
    expected_value: str
    observed_value: str
    anti_bias_detected: bool = Field(
        description="True if obsolete bias pattern was erroneously generated by model",
    )
    probe_passed: bool = Field(
        description="True if expected value matched and no bias patterns leaked",
    )
