"""Unit and integration tests for Sentinel Vouchers and Loopback Egress Proxy (AgentSentinelEgressGuard)."""

from __future__ import annotations

import asyncio
from pathlib import Path
import pytest

from myrm_agent_harness.core.security.egress.sentinel import (
    SENTINEL_PREFIX,
    SENTINEL_SUFFIX,
    SentinelManager,
    StreamingSentinelScanner,
    is_sentinel_voucher,
)
from myrm_agent_harness.core.security.egress.proxy_server import (
    EphemeralCaManager,
    LoopbackEgressProxy,
)
from myrm_agent_harness.toolkits.code_execution.security.env_isolation import (
    EnvInheritPolicy,
    build_isolated_child_env,
)


class TestSentinelManager:
    """Tests for in-memory AES-256-GCM sentinel voucher lifecycle."""

    def test_create_and_resolve_voucher(self) -> None:
        mgr = SentinelManager()
        secret = "sk-live-super-secret-token-12345"
        voucher = mgr.create_sentinel(secret, metadata={"type": "openai"})

        assert voucher.startswith(SENTINEL_PREFIX)
        assert voucher.endswith(SENTINEL_SUFFIX)
        assert secret not in voucher
        assert is_sentinel_voucher(voucher) is True

        resolved = mgr.resolve_sentinel(voucher)
        assert resolved == secret

    def test_deterministic_deduplication(self) -> None:
        mgr = SentinelManager()
        secret = "ghp_static_user_token_9999"
        v1 = mgr.create_sentinel(secret)
        v2 = mgr.create_sentinel(secret)
        assert v1 == v2

    def test_forged_or_tampered_voucher_rejected(self) -> None:
        mgr = SentinelManager()
        assert mgr.resolve_sentinel("myrm-sent-v1.forged_token.end") is None
        assert mgr.resolve_sentinel("not-a-sentinel") is None
        assert mgr.resolve_sentinel("") is None

    def test_different_process_keys_isolated(self) -> None:
        mgr1 = SentinelManager()
        mgr2 = SentinelManager()
        secret = "sensitive-credential"

        v1 = mgr1.create_sentinel(secret)
        # mgr2 cannot decrypt vouchers generated by mgr1
        assert mgr2.resolve_sentinel(v1) is None

    def test_substitute_text(self) -> None:
        mgr = SentinelManager()
        s1 = mgr.create_sentinel("REAL_KEY_1")
        s2 = mgr.create_sentinel("REAL_KEY_2")

        template = f"curl -H 'Authorization: Bearer {s1}' https://api.com/?token={s2}&other=clean"
        substituted = mgr.substitute_text(template)

        assert substituted == "curl -H 'Authorization: Bearer REAL_KEY_1' https://api.com/?token=REAL_KEY_2&other=clean"
        assert s1 not in substituted
        assert s2 not in substituted

    def test_substitute_bytes(self) -> None:
        mgr = SentinelManager()
        s1 = mgr.create_sentinel("SECRET_IN_BYTES")
        payload = f'{{"auth": "{s1}"}}'.encode("utf-8")

        replaced = mgr.substitute_bytes(payload)
        assert replaced == b'{"auth": "SECRET_IN_BYTES"}'


class TestStreamingSentinelScanner:
    """Tests for sliding-window token reconstruction across arbitrary TCP chunk splits."""

    def test_chunk_split_reconstruction(self) -> None:
        mgr = SentinelManager()
        raw_secret = "very-long-secret-api-key-987654321"
        voucher = mgr.create_sentinel(raw_secret)

        full_stream = f"HEADER_START|auth_token={voucher}|FOOTER_END".encode("utf-8")

        # Split into microscopic 5-byte chunks to stress boundary slicing
        chunks = [full_stream[i : i + 5] for i in range(0, len(full_stream), 5)]
        scanner = StreamingSentinelScanner(mgr)

        reconstructed = bytearray()
        for c in chunks:
            ready = scanner.feed(c)
            if ready:
                reconstructed.extend(ready)
        reconstructed.extend(scanner.flush())

        expected = f"HEADER_START|auth_token={raw_secret}|FOOTER_END".encode("utf-8")
        assert bytes(reconstructed) == expected


class TestChildEnvIsolationIntegration:
    """Validates that Sentinel vouchers pass child env isolation while raw secrets are blocked."""

    def test_raw_secrets_scrubbed_but_sentinels_allowed(self) -> None:
        mgr = SentinelManager()
        raw_token = "ghp_dangerous_token_leaked_plain"
        voucher = mgr.create_sentinel(raw_token)

        extra = {
            "OPENAI_API_KEY": "sk-plain-secret-must-be-blocked",
            "GITHUB_TOKEN": voucher,
            "SAFE_CUSTOM_VAR": "allowed_value",
            "HTTP_PROXY": "http://127.0.0.1:54321",
        }

        sanitized = build_isolated_child_env(
            base_env=None,
            extra_env=extra,
            inherit_policy=EnvInheritPolicy.CORE,
        )

        # Raw key blocked
        assert "OPENAI_API_KEY" not in sanitized
        # Sentinel voucher allowed (no raw secret)
        assert sanitized.get("GITHUB_TOKEN") == voucher
        assert sanitized.get("SAFE_CUSTOM_VAR") == "allowed_value"
        assert sanitized.get("HTTP_PROXY") == "http://127.0.0.1:54321"


class TestLoopbackEgressProxy:
    """Integration test for the loopback proxy substituting sentinels on live HTTP traffic."""

    @pytest.mark.asyncio
    async def test_proxy_lifecycle_and_ca_cleanup(self) -> None:
        proxy = LoopbackEgressProxy()
        url = await proxy.start()
        assert url.startswith("http://127.0.0.1:")

        ca_bundle = proxy.ca_bundle_path
        assert ca_bundle is not None
        assert Path(ca_bundle).exists()

        await proxy.stop()
        # Ephemeral CA file must be unlinked upon stop
        assert not Path(ca_bundle).exists()

    @pytest.mark.asyncio
    async def test_http_forward_substitutes_headers_and_body(self) -> None:
        """Run a mock upstream HTTP server and verify proxy transparently substitutes sentinels."""
        mgr = SentinelManager()
        secret_token = "actual-super-secret-token"
        secret_body = "actual-body-key"

        voucher_header = mgr.create_sentinel(secret_token)
        voucher_body = mgr.create_sentinel(secret_body)

        received_headers: dict[str, str] = {}
        received_body: bytearray = bytearray()

        # 1. Start mock target HTTP server
        async def mock_target_handler(reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None:
            while True:
                line = await reader.readline()
                if not line or line in (b"\r\n", b"\n"):
                    break
                line_str = line.decode("latin1").strip()
                if ":" in line_str:
                    k, v = line_str.split(":", 1)
                    received_headers[k.strip().lower()] = v.strip()

            content_len = int(received_headers.get("content-length", 0))
            if content_len > 0:
                body_bytes = await reader.read(content_len)
                received_body.extend(body_bytes)

            writer.write(b"HTTP/1.1 200 OK\r\nContent-Length: 2\r\n\r\nOK")
            await writer.drain()
            writer.close()
            await writer.wait_closed()

        upstream_server = await asyncio.start_server(mock_target_handler, host="127.0.0.1", port=0)
        upstream_port = upstream_server.sockets[0].getsockname()[1]

        # 2. Start loopback egress proxy
        proxy = LoopbackEgressProxy(sentinel_manager=mgr)
        proxy_url = await proxy.start()
        proxy_port = int(proxy_url.split(":")[-1])

        # 3. Client connects through proxy and sends vouchers
        try:
            c_reader, c_writer = await asyncio.open_connection("127.0.0.1", proxy_port)
            body_payload = f'{{"key": "{voucher_body}"}}'.encode("utf-8")
            req = (
                f"POST http://127.0.0.1:{upstream_port}/v1/chat HTTP/1.1\r\n"
                f"Host: 127.0.0.1:{upstream_port}\r\n"
                f"Authorization: Bearer {voucher_header}\r\n"
                f"Content-Length: {len(body_payload)}\r\n"
                f"\r\n"
            ).encode("latin1") + body_payload

            c_writer.write(req)
            await c_writer.drain()

            resp = await c_reader.read(1024)
            assert b"200 OK" in resp

            # 4. Assert upstream received real secrets, not vouchers!
            assert received_headers.get("authorization") == f"Bearer {secret_token}"
            assert f'{{"key": "{secret_body}"}}'.encode("utf-8") in received_body

        finally:
            await proxy.stop()
            upstream_server.close()
            await upstream_server.wait_closed()
