"""Four-Tier Progressive Spend Control and Soft Quota Intervention Type Contracts.

[INPUT]
- None (Standard library dataclasses, enum, typing)

[OUTPUT]
- SpendInterventionTier: The 4-tier progressive intervention classification
- InterventionAction: Concrete response action dictated by the current tier
- SpendControlConfig: Configurable progressive spend tier thresholds and fallback settings
- SpendInterventionDecision: Decision artifact returned upon spend evaluation
- FleetQuotaItem: Fleet-wide quota and spend attribution record across dimensions

[POS]
Type definitions and data contracts for four-tier progressive spend control,
soft quota gates, seamless model downgrade, and fleet quota deck attribution.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum


class SpendInterventionTier(StrEnum):
    """The four progressive tiers of spend control and soft quota intervention."""

    TIER_1_VISIBILITY = "tier_1_visibility"        # Real-time visibility & model downgrade recommendation
    TIER_2_SOFT_GATE = "tier_2_soft_gate"          # Soft spend gate: one-click self-confirmation to proceed
    TIER_3_AUTO_DOWNGRADE = "tier_3_auto_downgrade"# Automatic seamless fallback to economy/efficient model
    TIER_4_CRITICAL_PAUSE = "tier_4_critical_pause"# High-risk safety pause with approval link generation


class InterventionAction(StrEnum):
    """Specific enforcement or guidance action resulting from tier evaluation."""

    ALLOW = "allow"                                # Normal execution allowed without intervention
    RECOMMEND_DOWNGRADE = "recommend_downgrade"    # Display warning & cost-saving suggestion
    REQUIRE_CONFIRMATION = "require_confirmation"  # Soft gate: wait for developer confirmation token
    SWITCH_MODEL = "switch_model"                  # Switch to economy model seamlessly
    PAUSE_FOR_APPROVAL = "pause_for_approval"      # Suspend session and require manager/admin sign-off


@dataclass(frozen=True, slots=True)
class SpendControlConfig:
    """Configurable thresholds and fallback parameters for four-tier spend control."""

    tier1_ratio: float = 0.70                      # 70% of quota triggers visibility / hint
    tier2_ratio: float = 0.90                      # 90% triggers soft confirmation gate
    tier3_ratio: float = 1.00                      # 100% triggers seamless model downgrade
    tier4_ratio: float = 1.30                      # 130% triggers critical pause & approval link
    downgrade_model_id: str = "gpt-4o-mini"         # Fallback model for Tier 3 continuation


@dataclass(frozen=True, slots=True)
class SpendInterventionDecision:
    """Decision output generated by evaluating current spend against quota limits."""

    tier: SpendInterventionTier
    action: InterventionAction
    current_spend_usd: float
    quota_limit_usd: float
    spend_ratio: float
    message: str
    downgrade_model_id: str | None = None
    bypass_token: str | None = None
    approval_token: str | None = None
    is_blocked: bool = False
    decision_id: str = field(default_factory=lambda: f"dec_{uuid.uuid4().hex[:12]}")
    created_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())


@dataclass(frozen=True, slots=True)
class FleetQuotaItem:
    """Aggregated quota and consumption status for a fleet dimension (profile, member, or task)."""

    dimension: str                                 # "agent_profile" | "member" | "task_type"
    identifier: str                                # e.g. "coder_agent", "user_102", "code_review"
    spend_usd: float
    allocated_quota_usd: float
    tier: SpendInterventionTier
    active_sessions: int = 1
    updated_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    @property
    def utilization_pct(self) -> float:
        """Calculate quota utilization percentage."""
        if self.allocated_quota_usd <= 0:
            return 0.0
        return round((self.spend_usd / self.allocated_quota_usd) * 100, 2)
