"""Reasoning trace stripper for removing chain-of-thought blocks from context and summaries.

Guarantees that:
1. Reasoning traces (<think>, <thought>, <reasoning>) never reach the summarizer prompt.
2. Traces emitted by the summarizer model are stripped before storing in cumulative summaries.
"""

from __future__ import annotations

import re

from myrm_agent_harness.runtime.context.lean_tail_compression_types import (
    ReasoningTagKind,
    StrippedMessageResult,
)


class ReasoningTraceStripper:
    """Robust regex-based recursive stripper for reasoning and CoT markup."""

    def __init__(self, target_tags: set[ReasoningTagKind] | None = None) -> None:
        self.target_tags = target_tags or {
            ReasoningTagKind.THINK,
            ReasoningTagKind.THOUGHT,
            ReasoningTagKind.REASONING,
            ReasoningTagKind.INTERNAL_COT,
        }
        self._compiled_patterns = self._compile_patterns()

    def strip_text(self, text: str) -> tuple[str, int, int]:
        """Strip all reasoning blocks from text.

        Returns (cleaned_text, stripped_chars, tags_count).
        """
        if not text:
            return "", 0, 0

        cleaned = text
        total_stripped_chars = 0
        total_tags_count = 0

        # Repeatedly apply patterns to handle possible nesting
        changed = True
        iterations = 0
        max_iterations = 5

        while changed and iterations < max_iterations:
            changed = False
            iterations += 1

            for pattern in self._compiled_patterns:
                matches = list(pattern.finditer(cleaned))
                if matches:
                    changed = True
                    total_tags_count += len(matches)
                    for m in matches:
                        total_stripped_chars += len(m.group(0))
                    cleaned = pattern.sub("", cleaned)

        # Handle unclosed tags at the end of text (e.g. streaming truncated output)
        cleaned, unclosed_chars, unclosed_tags = self._strip_unclosed_tags(cleaned)
        total_stripped_chars += unclosed_chars
        total_tags_count += unclosed_tags

        # Clean up excess whitespace created by block removals
        cleaned = re.sub(r"\n{3,}", "\n\n", cleaned).strip()

        return cleaned, total_stripped_chars, total_tags_count

    def strip_message(self, message: dict[str, str]) -> StrippedMessageResult:
        """Strip reasoning traces from a single message dictionary."""
        role = message.get("role", "")
        content = message.get("content", "")

        cleaned_text, stripped_chars, tags_count = self.strip_text(content)

        return StrippedMessageResult(
            role=role,
            cleaned_content=cleaned_text,
            stripped_chars_count=stripped_chars,
            tags_removed_count=tags_count,
        )

    def strip_messages(
        self, messages: list[dict[str, str]]
    ) -> list[dict[str, str]]:
        """Batch strip reasoning traces from history before feeding to summarizer prompt."""
        result: list[dict[str, str]] = []
        for msg in messages:
            cleaned_msg = dict(msg)
            stripped_res = self.strip_message(msg)
            cleaned_msg["content"] = stripped_res.cleaned_content
            # Preserve message even if content is empty, or ensure empty string
            result.append(cleaned_msg)
        return result

    def strip_summarizer_output(self, raw_summary: str) -> str:
        """Strip any thoughts generated by the summarizer itself before persisting."""
        cleaned, _, _ = self.strip_text(raw_summary)
        return cleaned

    def _compile_patterns(self) -> list[re.Pattern[str]]:
        """Compile regex patterns for configured reasoning tags."""
        patterns: list[re.Pattern[str]] = []
        for tag in self.target_tags:
            tag_name = re.escape(tag.value)
            # Match <tag>...</tag> case-insensitively across lines
            pat = re.compile(
                rf"<{tag_name}(?:\s+[^>]*)?>[\s\S]*?</{tag_name}>",
                re.IGNORECASE,
            )
            patterns.append(pat)
        return patterns

    def _strip_unclosed_tags(self, text: str) -> tuple[str, int, int]:
        """Strip trailing unclosed tags caused by mid-stream interruptions."""
        cleaned = text
        unclosed_chars = 0
        unclosed_tags = 0

        for tag in self.target_tags:
            tag_name = re.escape(tag.value)
            # Find an opening tag that does not have a corresponding closing tag
            open_pat = re.compile(rf"<{tag_name}(?:\s+[^>]*)?>[\s\S]*$", re.IGNORECASE)
            match = open_pat.search(cleaned)
            if match and f"</{tag_name}>" not in match.group(0):
                unclosed_chars += len(match.group(0))
                unclosed_tags += 1
                cleaned = open_pat.sub("", cleaned)

        return cleaned, unclosed_chars, unclosed_tags
