"""Tests for LocalExecutor error diagnostics via ExecutionResult.error_hint.

Hints are generated by ExecutionResult.__post_init__ (models.py) — not by the
executor itself — so these tests verify the integrated pipeline: execute() →
ExecutionResult auto-classification → error_hint populated.
"""

from unittest.mock import AsyncMock, patch

import pytest

from myrm_agent_harness.toolkits.code_execution.config import ExecutionConfig
from myrm_agent_harness.toolkits.code_execution.executors.local.executor import LocalExecutor
from myrm_agent_harness.toolkits.code_execution.executors.models import ExecutionContext


@pytest.mark.asyncio
async def test_local_executor_module_not_found_uses_error_hint():
    """ModuleNotFoundError → error_category='import' + error_hint with install command."""
    executor = LocalExecutor(ExecutionConfig())
    context = ExecutionContext(session_id="test_session", code="import requests")

    with patch("myrm_agent_harness.toolkits.code_execution.executors.local.executor.asyncio.create_subprocess_exec") as mock_exec:
        mock_process = AsyncMock()
        mock_process.communicate.return_value = (b"", b"Traceback (most recent call last):\nModuleNotFoundError: No module named 'requests'")
        mock_process.returncode = 1
        mock_exec.return_value = mock_process

        result = await executor.execute(context)

        assert not result.success
        assert result.error_category == "import"
        assert result.error_hint is not None
        assert "requests" in result.error_hint
        assert "install" in result.error_hint


@pytest.mark.asyncio
async def test_local_executor_pypi_mapping_in_hint():
    """PIL import → error_hint suggests 'Pillow' (via _IMPORT_TO_PYPI)."""
    executor = LocalExecutor(ExecutionConfig())
    context = ExecutionContext(session_id="test_session", code="from PIL import Image")

    with patch("myrm_agent_harness.toolkits.code_execution.executors.local.executor.asyncio.create_subprocess_exec") as mock_exec:
        mock_process = AsyncMock()
        mock_process.communicate.return_value = (b"", b"ModuleNotFoundError: No module named 'PIL'")
        mock_process.returncode = 1
        mock_exec.return_value = mock_process

        result = await executor.execute(context)

        assert not result.success
        assert result.error_category == "import"
        assert result.error_hint is not None
        assert "Pillow" in result.error_hint


@pytest.mark.asyncio
async def test_local_executor_no_hint_for_syntax_errors():
    executor = LocalExecutor(ExecutionConfig())
    context = ExecutionContext(session_id="test_session", code="print('hello'")

    with patch("myrm_agent_harness.toolkits.code_execution.executors.local.executor.asyncio.create_subprocess_exec") as mock_exec:
        mock_process = AsyncMock()
        mock_process.communicate.return_value = (b"", b"SyntaxError: invalid syntax")
        mock_process.returncode = 1
        mock_exec.return_value = mock_process

        result = await executor.execute(context)

        assert not result.success
        assert result.error_category == "syntax"
        assert result.error_hint is None


@pytest.mark.asyncio
async def test_local_executor_success():
    executor = LocalExecutor(ExecutionConfig())
    context = ExecutionContext(session_id="test_session", code="print('hello')")

    with patch("myrm_agent_harness.toolkits.code_execution.executors.local.executor.asyncio.create_subprocess_exec") as mock_exec:
        mock_process = AsyncMock()
        mock_process.communicate.return_value = (b"hello\n", b"")
        mock_process.returncode = 0
        mock_exec.return_value = mock_process

        result = await executor.execute(context)

        assert result.success
        assert result.stdout == "hello\n"
        assert result.stderr == ""
        assert result.error_hint is None
