"""Browser pool configuration.

[INPUT]
- dataclasses::dataclass, field (POS: Python dataclass)
- enum::StrEnum (POS: Python string enum)

[OUTPUT]
- BrowserMode: browser runtime mode enum
- LaunchMode: browser launch method enum (launch/connect/auto)
- ThrottleMode: throttle mode enum
- RateLimiterConfig: rate limiter config
- MemoryGuardConfig: memory guard config
- CircuitBreakerConfig: circuit breaker config
- ResourceBlockConfig: resource blocking config
- NavigationWaitConfig: navigation wait config
- RobustnessPolicy: explicit combination of throttle, memory guard, and circuit breaker (generated by mode factory)
- BrowserConfig: top-level browser pool config (with with_mode, default_emulation, structural mode/robustness validation)
- BrowserPoolConfig: same type as BrowserConfig (public type name)

[POS]
Browser pool configuration module. Public presets: `BrowserConfig.minimal()` / `standard()` / `defensive()`; parameterless `BrowserConfig()` matches `standard()` field values.
`RobustnessPolicy.from_mode` and construction-time structural validation both read from the same `_MODE_BLUEPRINTS` table.
`robustness` is an explicit `RobustnessPolicy` (`None` triggers auto-fill from `mode` in `__post_init__`).
`mode` and `robustness` must agree on throttle tier / memory guard toggle / circuit breaker toggle; numeric values can be fine-tuned via `dataclasses.replace` without changing those toggles.
Switch `BrowserMode` via `BrowserConfig.with_mode()`, or replace both `mode` and `RobustnessPolicy.from_mode(mode)`.

`launch_mode` controls browser instance acquisition:
- LAUNCH: always starts a new Chromium process (SaaS sandbox default)
- CONNECT: connects to user's running Chrome via CDP
- AUTO: probes CDP first, connect on success, fallback to launch on failure (Local/Tauri default)
"""

from __future__ import annotations

import dataclasses
from dataclasses import dataclass, field
from enum import StrEnum
from types import MappingProxyType
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .emulation import EmulationConfig

MAX_CONTEXTS_PER_BROWSER = 5
MAX_PAGES_PER_CONTEXT = 5
SCALE_OUT_LOAD_THRESHOLD = 10


class BrowserMode(StrEnum):
    """Browser runtime mode."""

    MINIMAL = "minimal"
    STANDARD = "standard"
    DEFENSIVE = "defensive"


class BrowserEngine(StrEnum):
    """Browser engine type.

    - CHROMIUM_PATCHRIGHT: Default engine based on Chromium (via patchright)
    - FIREFOX_CAMOUFOX: High-stealth engine based on Firefox (via camoufox)
    """

    CHROMIUM_PATCHRIGHT = "chromium_patchright"
    FIREFOX_CAMOUFOX = "firefox_camoufox"


class LaunchMode(StrEnum):
    """BrowserInstanceGet方式.

    - LAUNCH: 始终new启 Chromium（SaaS 沙箱Default）
    - CONNECT:  via  CDP Connection用户 already 运行  Chrome
    - AUTO: 先探测 CDP → Success则 connect → Failure则 fallback  to  launch（Local/Tauri Default）
    - REMOTE: 连接到远程云端浏览器（如 Browserbase/Browser Use）通过 WebSocket
    - EXTENSION: 通过官方浏览器扩展的 WebSocket CDP 代理获取用户日常浏览器控制权
    """

    LAUNCH = "launch"
    CONNECT = "connect"
    AUTO = "auto"
    REMOTE = "remote"
    EXTENSION = "extension"


_DEFAULT_CDP_ENDPOINT = "http://127.0.0.1:9222"


class ThrottleMode(StrEnum):
    """限流Mode."""

    NONE = "none"
    DOMAIN = "domain"


@dataclass(frozen=True)
class RateLimiterConfig:
    """限流Configure."""

    mode: ThrottleMode = ThrottleMode.NONE
    domain_qps: float = 5.0
    domain_burst: int = 10


@dataclass(frozen=True)
class MemoryGuardConfig:
    """内存监控Configure."""

    enabled: bool = False
    max_memory_percent: float = 85.0
    check_interval: int = 5

    def __post_init__(self) -> None:
        if not 50.0 <= self.max_memory_percent <= 99.0:
            msg = f"max_memory_percent must be in [50, 99], got {self.max_memory_percent}"
            raise ValueError(msg)
        if self.check_interval <= 0:
            msg = f"check_interval must be > 0, got {self.check_interval}"
            raise ValueError(msg)


@dataclass(frozen=True)
class CircuitBreakerConfig:
    """熔断器Configure."""

    enabled: bool = False
    failure_threshold: int = 3
    timeout: float = 30.0

    def __post_init__(self) -> None:
        if self.failure_threshold < 1:
            msg = f"failure_threshold must be >= 1, got {self.failure_threshold}"
            raise ValueError(msg)
        if self.timeout <= 0:
            msg = f"timeout must be > 0, got {self.timeout}"
            raise ValueError(msg)


@dataclass(frozen=True)
class ResourceBlockConfig:
    """资源拦截Configure."""

    block_images: bool = False
    block_stylesheets: bool = False
    block_scripts: bool = False
    block_fonts: bool = False
    block_media: bool = False
    block_ad_domains: bool = False


@dataclass(frozen=True)
class NavigationWaitConfig:
    """导航WaitStrategyConfigure.

    Support多种WaitStrategy:
    - smart: 自适应检测（推荐，fast+准确）- 先尝试fastnetworkidle，Failure则degradationhybrid
    - hybrid: 混合检测（平衡Mode）- DOMstable+网络Empty闲双重保障
    - dom_stable: OnlyDOMstable（适合StaticPage）
    - networkidle: Only网络Empty闲（compatibleMode）

    TimeoutConfigure适配 not 同可靠性要求：
    - MINIMAL: 1000ms（fastMode）
    - STANDARD: 2000ms（standardMode）
    - DEFENSIVE: 3000ms（防御Mode）

    grace_period_ms: 混合Strategy in ，第一个任务Complete后给第二个任务 额外Wait时间
    """

    wait_timeout_ms: int = 2000
    strategy: str = "smart"  # "networkidle" | "dom_stable" | "hybrid" | "smart"（推荐）
    quiet_ms: int = 500  # DOMstable静默期
    grace_period_ms: int = 200  # 混合Strategygrace period

    def __post_init__(self) -> None:
        if not 100 <= self.wait_timeout_ms <= 10_000:
            msg = f"wait_timeout_ms must be in [100, 10000], got {self.wait_timeout_ms}"
            raise ValueError(msg)

        if self.strategy not in ("networkidle", "dom_stable", "hybrid", "smart"):
            msg = f"strategy must be one of ('networkidle', 'dom_stable', 'hybrid', 'smart'), got {self.strategy!r}"
            raise ValueError(msg)

        if not 100 <= self.quiet_ms <= 2000:
            msg = f"quiet_ms must be in [100, 2000], got {self.quiet_ms}"
            raise ValueError(msg)

        if not 0 <= self.grace_period_ms <= 1000:
            msg = f"grace_period_ms must be in [0, 1000], got {self.grace_period_ms}"
            raise ValueError(msg)


def _default_emulation_for_mode(mode: BrowserMode) -> EmulationConfig | None:
    """Default emulation config per mode.

    Standard/Defensive grant clipboard permissions for headed-mode compatibility
    (Clipboard API requires explicit permission in non-headless Chromium).
    """
    if mode == BrowserMode.MINIMAL:
        return None
    from .emulation import EmulationConfig

    return EmulationConfig(permissions=("clipboard-read", "clipboard-write"))


def _resource_block_none() -> ResourceBlockConfig:
    return ResourceBlockConfig()


def _resource_block_standard() -> ResourceBlockConfig:
    return ResourceBlockConfig(
        block_images=True,
        block_stylesheets=False,
        block_fonts=True,
        block_media=True,
        block_scripts=False,
        block_ad_domains=True,
    )


@dataclass(frozen=True)
class _ModeRobustnessBlueprint:
    """Per-mode structural switches: throttle tier, memory guard and circuit breaker on/off."""

    throttle: ThrottleMode
    memory_guard_enabled: bool
    circuit_breaker_enabled: bool


def _navigation_wait_for_mode(mode: BrowserMode) -> NavigationWaitConfig:
    """Default navigation wait config for given mode."""
    if mode == BrowserMode.MINIMAL:
        return NavigationWaitConfig(wait_timeout_ms=1000)
    elif mode == BrowserMode.STANDARD:
        return NavigationWaitConfig(wait_timeout_ms=2000)
    else:
        return NavigationWaitConfig(wait_timeout_ms=3000)


_MODE_BLUEPRINTS: MappingProxyType[BrowserMode, _ModeRobustnessBlueprint] = MappingProxyType(
    {
        BrowserMode.MINIMAL: _ModeRobustnessBlueprint(
            throttle=ThrottleMode.NONE,
            memory_guard_enabled=False,
            circuit_breaker_enabled=False,
        ),
        BrowserMode.STANDARD: _ModeRobustnessBlueprint(
            throttle=ThrottleMode.DOMAIN,
            memory_guard_enabled=False,
            circuit_breaker_enabled=False,
        ),
        BrowserMode.DEFENSIVE: _ModeRobustnessBlueprint(
            throttle=ThrottleMode.DOMAIN,
            memory_guard_enabled=True,
            circuit_breaker_enabled=True,
        ),
    },
)


def _default_rate_limiter(throttle: ThrottleMode) -> RateLimiterConfig:
    if throttle == ThrottleMode.NONE:
        return RateLimiterConfig(mode=ThrottleMode.NONE)
    return RateLimiterConfig(mode=ThrottleMode.DOMAIN, domain_qps=5.0, domain_burst=10)


def _default_memory_guard(enabled: bool) -> MemoryGuardConfig:
    if enabled:
        return MemoryGuardConfig(enabled=True, max_memory_percent=85.0, check_interval=5)
    return MemoryGuardConfig(enabled=False)


def _default_circuit_breaker(enabled: bool) -> CircuitBreakerConfig:
    if enabled:
        return CircuitBreakerConfig(enabled=True, failure_threshold=3, timeout=30.0)
    return CircuitBreakerConfig(enabled=False)


def _blueprint_for_mode(mode: BrowserMode) -> _ModeRobustnessBlueprint:
    try:
        return _MODE_BLUEPRINTS[mode]
    except KeyError as e:
        msg = f"Unknown BrowserMode for robustness blueprint: {mode!r}"
        raise KeyError(msg) from e


@dataclass(frozen=True)
class RobustnessPolicy:
    """导航 and 池related 鲁棒性Strategy（显式Field，可由Mode工厂Generate）."""

    rate_limiter: RateLimiterConfig
    memory_guard: MemoryGuardConfig
    circuit_breaker: CircuitBreakerConfig

    @classmethod
    def from_mode(cls, mode: BrowserMode) -> RobustnessPolicy:
        """Default policy for `mode`, derived from `_MODE_BLUEPRINTS`."""
        return _policy_from_blueprint(_blueprint_for_mode(mode))


def _policy_from_blueprint(bp: _ModeRobustnessBlueprint) -> RobustnessPolicy:
    """Instantiate `RobustnessPolicy` from blueprint switches and module default numeric fields."""
    return RobustnessPolicy(
        rate_limiter=_default_rate_limiter(bp.throttle),
        memory_guard=_default_memory_guard(bp.memory_guard_enabled),
        circuit_breaker=_default_circuit_breaker(bp.circuit_breaker_enabled),
    )


def _robustness_structurally_matches_mode(policy: RobustnessPolicy, mode: BrowserMode) -> bool:
    bp = _blueprint_for_mode(mode)
    return (
        policy.rate_limiter.mode == bp.throttle
        and policy.memory_guard.enabled == bp.memory_guard_enabled
        and policy.circuit_breaker.enabled == bp.circuit_breaker_enabled
    )


@dataclass(frozen=True)
class BrowserConfig:
    """Browser pool top-level configuration.

    Fields: mode, launch_mode, cdp_endpoint, max_concurrent_pages, resource_block,
    default_emulation, navigation_wait, robustness (optional; filled from mode when None).

    ``default_emulation`` provides fallback EmulationConfig (e.g. clipboard permissions)
    applied to every BrowserContext created by ContextFactory when the caller does not
    pass an explicit emulation parameter. Standard/Defensive modes grant clipboard-read
    and clipboard-write by default for headed-mode (Tauri/CONNECT) compatibility.

    Structural invariant: throttle tier and memory/circuit-breaker on-off flags must match BrowserMode;
    use with_mode() to change mode. Numeric tuning may use dataclasses.replace without changing those switches.

    Presets: use class methods minimal(), standard(), defensive() only.
    """

    mode: BrowserMode = BrowserMode.STANDARD
    engine: BrowserEngine = BrowserEngine.CHROMIUM_PATCHRIGHT
    launch_mode: LaunchMode = LaunchMode.LAUNCH
    cdp_endpoint: str | None = None
    remote_ws_endpoint: str | None = None
    remote_ws_headers: dict[str, str] | None = None
    extension_ws_endpoint: str | None = None
    extension_auth_token: str | None = None
    max_concurrent_pages: int = 30
    idle_timeout_seconds: int = 300
    resource_block: ResourceBlockConfig = field(default_factory=_resource_block_standard)
    default_emulation: EmulationConfig | None = None
    navigation_wait: NavigationWaitConfig | None = None
    robustness: RobustnessPolicy | None = None

    def __post_init__(self) -> None:
        if not 1 <= self.max_concurrent_pages <= 100:
            msg = f"max_concurrent_pages must be in [1, 100], got {self.max_concurrent_pages}"
            raise ValueError(msg)
        if self.idle_timeout_seconds < 0:
            msg = f"idle_timeout_seconds must be >= 0 (0 disables idle eviction), got {self.idle_timeout_seconds}"
            raise ValueError(msg)
        if self.default_emulation is None:
            object.__setattr__(self, "default_emulation", _default_emulation_for_mode(self.mode))
        if self.navigation_wait is None:
            object.__setattr__(self, "navigation_wait", _navigation_wait_for_mode(self.mode))
        if self.robustness is None:
            object.__setattr__(self, "robustness", RobustnessPolicy.from_mode(self.mode))
        elif not _robustness_structurally_matches_mode(self.robustness, self.mode):
            msg = (
                "robustness is not structurally compatible with mode "
                f"{self.mode!r}: expected throttle/memory_guard/circuit_breaker "
                "on-off pattern for this BrowserMode. Use BrowserConfig.with_mode() "
                "when changing mode, or pass robustness=RobustnessPolicy.from_mode(mode)."
            )
            raise ValueError(msg)

    def _resolved_robustness(self) -> RobustnessPolicy:
        """Return effective robustness; raises if invariant is broken."""
        r = self.robustness
        if r is None:
            msg = "BrowserConfig.robustness is unset after initialization"
            raise RuntimeError(msg)
        return r

    @property
    def rate_limiter(self) -> RateLimiterConfig:
        return self._resolved_robustness().rate_limiter

    @property
    def memory_guard(self) -> MemoryGuardConfig:
        return self._resolved_robustness().memory_guard

    @property
    def circuit_breaker(self) -> CircuitBreakerConfig:
        return self._resolved_robustness().circuit_breaker

    def with_mode(self, mode: BrowserMode) -> BrowserConfig:
        """Return a new config: same max_concurrent_pages and resource_block, mode and default robustness/navigation_wait/emulation updated."""
        return dataclasses.replace(
            self,
            mode=mode,
            default_emulation=_default_emulation_for_mode(mode),
            navigation_wait=_navigation_wait_for_mode(mode),
            robustness=RobustnessPolicy.from_mode(mode),
        )

    @classmethod
    def minimal(cls) -> BrowserConfig:
        return cls(
            mode=BrowserMode.MINIMAL,
            max_concurrent_pages=10,
            resource_block=_resource_block_none(),
            default_emulation=_default_emulation_for_mode(BrowserMode.MINIMAL),
            navigation_wait=_navigation_wait_for_mode(BrowserMode.MINIMAL),
            robustness=RobustnessPolicy.from_mode(BrowserMode.MINIMAL),
        )

    @classmethod
    def standard(cls) -> BrowserConfig:
        return cls(
            mode=BrowserMode.STANDARD,
            max_concurrent_pages=30,
            resource_block=_resource_block_standard(),
            default_emulation=_default_emulation_for_mode(BrowserMode.STANDARD),
            navigation_wait=_navigation_wait_for_mode(BrowserMode.STANDARD),
            robustness=RobustnessPolicy.from_mode(BrowserMode.STANDARD),
        )

    @classmethod
    def defensive(cls) -> BrowserConfig:
        return cls(
            mode=BrowserMode.DEFENSIVE,
            max_concurrent_pages=50,
            resource_block=_resource_block_standard(),
            default_emulation=_default_emulation_for_mode(BrowserMode.DEFENSIVE),
            navigation_wait=_navigation_wait_for_mode(BrowserMode.DEFENSIVE),
            robustness=RobustnessPolicy.from_mode(BrowserMode.DEFENSIVE),
        )


BrowserPoolConfig = BrowserConfig
