"""Workspace data models for code execution sessions.

Defines the workspace data structures:
- Workspace: workspace model (dataclass)
- WorkspaceStatus: workspace status enum
- WorkspaceDict: serialization dict type (TypedDict)

Workspace path: ``workspaces/{session_id}/`` relative to the storage root.
session_id is generated by the business layer (e.g. ``user_alice_chat_123``);
the framework only consumes it.

[INPUT]
- (none)

[OUTPUT]
- WorkspaceDict: Serialized workspace dictionary type.
- WorkspaceStatus: Workspace lifecycle status.
- Workspace: Logical workspace for a code execution session.

[POS]
Workspace data models for code execution sessions.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum
from typing import TypedDict

from myrm_agent_harness.toolkits.code_execution.security import validate_path_component


class WorkspaceDict(TypedDict):
    """Serialized workspace dictionary type."""

    id: str
    session_id: str
    status: str
    path: str
    created_at: str
    last_used_at: str


class WorkspaceStatus(StrEnum):
    """Workspace lifecycle status."""

    ACTIVE = "active"
    DELETED = "deleted"


@dataclass
class Workspace:
    """Logical workspace for a code execution session.

    Represents a temporary file storage space bound to a session_id.
    The framework uses session_id as the sole identifier; business concepts
    like user_id or chat_id are composed into session_id by the caller.

    Directory layout inside the workspace::

        workspace/
        ├── .claude/skills/    # preloaded skills
        ├── sessions/          # execution artifacts
        └── user_files/        # synced user files
    """

    id: str
    session_id: str

    status: WorkspaceStatus = WorkspaceStatus.ACTIVE
    path: str = ""

    created_at: datetime = field(default_factory=datetime.now)
    last_used_at: datetime = field(default_factory=datetime.now)

    def __post_init__(self) -> None:
        """Validate path components and build workspace path."""
        workspace_id_validation = validate_path_component(self.id, "workspace_id")
        if not workspace_id_validation.is_safe:
            raise ValueError(f"Invalid workspace_id: {workspace_id_validation.reason}")

        if not self.session_id:
            raise ValueError("session_id is required")

        session_id_validation = validate_path_component(self.session_id, "session_id")
        if not session_id_validation.is_safe:
            raise ValueError(f"Invalid session_id: {session_id_validation.reason}")

        if not self.path:
            self.path = f"workspaces/{self.session_id}"

    def to_dict(self) -> WorkspaceDict:
        """Serialize to dictionary (ISO 8601 timestamps)."""
        return {  # type: ignore[return-value]
            "id": self.id,
            "session_id": self.session_id,
            "status": self.status.value,
            "path": self.path,
            "created_at": self.created_at.isoformat(),
            "last_used_at": self.last_used_at.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict[str, object]) -> "Workspace":
        """Deserialize from dictionary."""
        return cls(
            id=str(data["id"]),
            session_id=str(data["session_id"]),
            status=WorkspaceStatus(str(data.get("status", "active"))),
            path=str(data.get("path", "")),
            created_at=datetime.fromisoformat(str(data["created_at"])),
            last_used_at=datetime.fromisoformat(str(data["last_used_at"])),
        )
